export const origin = 'https://www.freefloorplan3d.com';
export const icon = (name, cls='') => `<svg class="icon ${cls}" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${({plan:'<path d="M3 3h18v18H3zM3 13h9V3m0 10v8m0-8h9"/>',cube:'<path d="m12 2 10 5v10l-10 5-10-5V7Zm0 10v10M2 7l10 5 10-5M7 4.5l10 5v5"/>',arrow:'<path d="M4 12h16m-6-6 6 6-6 6"/>',download:'<path d="M12 3v12m-5-5 5 5 5-5M4 15v6h16v-6"/>',check:'<path d="m5 12 4 4L19 6"/>',ruler:'<path d="m3 17 14-14 4 4L7 21Zm8-10 3 3m-7 1 3 3m-7 1 3 3"/>',spark:'<path d="m12 3 2.5 6.5L21 12l-6.5 2.5L12 21l-2.5-6.5L3 12l6.5-2.5ZM20 2v4m-2-2h4"/>',layers:'<path d="m12 2 10 5-10 5L2 7Zm-10 10 10 5 10-5M2 17l10 5 10-5"/>',clock:'<circle cx="12" cy="12" r="9"/><path d="M12 7v5l3 2"/>'})[name]||''}</svg>`;
const brand = `<a class="brand" href="/" aria-label="FreeFloorplan3D home"><img class="brand-logo" src="/assets/brand-icon.png" width="44" height="44" alt=""><span>FreeFloorplan<span class="blue">3D</span><span class="brand-dot">.</span></span></a>`;
const header = `<a class="skip" href="#main">Skip to content</a><header class="header"><div class="container nav">${brand}<nav aria-label="Main navigation"><a href="/#how-it-works">How it works</a><a href="/guides/">Planning guides</a><a href="/#faq">FAQs</a></nav><a class="button small" href="/planner/">Explore the planner ${icon('arrow')}</a></div></header>`;
const footer = `<footer><div class="container footer-top"><div>${brand}<p>More possibilities for every square metre.<br>Free 2D &amp; 3D floorplanning. Coming soon.</p></div><div><h3>Start imagining</h3><a href="/planner/">Floorplan creator — coming soon</a><a href="/guides/">Floorplan planning guides</a><a href="/#faq">Your questions, answered</a></div><div><h3>The details</h3><a href="/privacy/">Privacy</a><a href="/downloads/measurement-checklist.txt" download>Free measurement checklist</a></div></div><div class="container footer-bottom"><span>© ${new Date().getUTCFullYear()} FreeFloorplan3D</span><span>Made for your next “what if?”</span></div></footer>`;
export function layout({title,description,path='/',body,type='WebPage',noindex=false}) {
  const schema={'@context':'https://schema.org','@graph':[{'@type':'Organization','@id':origin+'/#organization',name:'FreeFloorplan3D',url:origin+'/'},{'@type':'WebSite','@id':origin+'/#website',name:'FreeFloorplan3D',url:origin+'/',publisher:{'@id':origin+'/#organization'}},{'@type':type,'@id':origin+path+'#page',url:origin+path,name:title,description,inLanguage:'en',isPartOf:{'@id':origin+'/#website'}}]};
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${title}</title><meta name="description" content="${description}"><link rel="canonical" href="${origin}${path}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow,max-image-preview:large'}"><meta name="theme-color" content="#2458ed"><meta property="og:title" content="${title}"><meta property="og:description" content="${description}"><meta property="og:type" content="website"><meta property="og:url" content="${origin}${path}"><meta property="og:site_name" content="FreeFloorplan3D"><meta name="twitter:card" content="summary"><link rel="icon" href="/favicon-48.png" type="image/png" sizes="48x48"><link rel="icon" href="/favicon-192.png" type="image/png" sizes="192x192"><link rel="apple-touch-icon" href="/apple-touch-icon.png" sizes="180x180"><link rel="stylesheet" href="/styles.css"><script type="application/ld+json">${JSON.stringify(schema).replace(/</g,'\\u003c')}</script><script src="/script.js" defer></script></head><body>${header}<main id="main">${body.replaceAll('<span class="coming-icon">'+icon('spark')+'</span>','<img class="workspace-logo" src="/assets/brand-icon.png" width="72" height="72" alt="FreeFloorplan3D">').replaceAll('<span class="coming-icon">'+icon('plan')+'</span>','<img class="workspace-logo" src="/assets/brand-icon.png" width="72" height="72" alt="FreeFloorplan3D">')}</main>${footer}</body></html>`;
}
const status = `<span class="status"><span></span> IN DEVELOPMENT · COMING SOON</span>`;
const plan = `<svg class="floorplan" viewBox="0 0 640 430" role="img" aria-label="Illustrative two-bedroom 2D floorplan with living room, kitchen, bathroom and entrance. Not to scale."><defs><pattern id="grid" width="20" height="20" patternUnits="userSpaceOnUse"><path d="M20 0H0V20" fill="none" stroke="#e1e9f6" stroke-width=".7"/></pattern></defs><path fill="url(#grid)" d="M0 0h640v430H0z"/><g stroke="#1e3a66" stroke-width="6" fill="#fff"><path d="M90 60h460v310H90z"/><path d="M365 60v310M365 215h185M90 170h170V60"/></g><path d="M260 60h105v110H260z" fill="#e7f0ff"/><path d="M98 178h259v184H98z" fill="#f0f5ff"/><g stroke="#92abe0" fill="#dae6ff" stroke-width="2"><rect x="416" y="80" width="90" height="89" rx="4"/><path d="M420 96h82m-42-14v14"/><rect x="416" y="236" width="90" height="89" rx="4"/><path d="M420 251h82m-42-14v14"/><rect x="116" y="215" width="48" height="98" rx="6"/><rect x="178" y="241" width="50" height="50" rx="8"/><rect x="108" y="76" width="136" height="25" rx="3"/><rect x="108" y="101" width="25" height="48" rx="3"/><rect x="277" y="76" width="70" height="32" rx="8"/><circle cx="304" cy="140" r="13"/></g><g stroke="#fff" stroke-width="8"><path d="M365 176v30m0 133v27M196 170h38M306 170h30M286 370h35"/></g><g stroke="#6c8ece" fill="none" stroke-width="1.4"><path d="M365 176h-29a29 29 0 0 0 29 29M365 339h-27a27 27 0 0 0 27 27M286 370v-35a35 35 0 0 1 35 35"/><path d="M90 38h460M90 31v14m460-14v14M577 60v310m-7-310h14m-14 310h14"/></g><g fill="#40557a" font-family="Arial,sans-serif" text-anchor="middle" font-size="14"><text x="320" y="28">ILLUSTRATIVE LAYOUT · NOT TO SCALE</text><text x="180" y="130">Kitchen</text><text x="307" y="161" font-size="12">Bath</text><text x="459" y="198">Bedroom 1</text><text x="459" y="349">Bedroom 2</text><text x="237" y="335">Living &amp; dining</text><text x="320" y="405">A clearer view of how rooms connect</text></g></svg>`;
export const home = () => layout({title:'Free Floorplan & Free Floorplan 3D Creator | Coming Soon',description:'Meet FreeFloorplan3D: free 2D and 3D floorplan software in development, with free image downloads planned. Explore the vision and prepare your first floorplan.',body:`
<section class="hero container"><div class="hero-copy">${status}<h1>A free floorplan.<br>A whole new<br><span class="blue">perspective.</span></h1><p class="lead">Big ideas start with a simple plan. Create your building’s floorplan in 2D, explore it in 3D, and download your images. <strong>All completely free.</strong></p><div class="actions"><a class="button" href="/planner/">Meet your future planner ${icon('arrow')}</a><a class="text-link" href="#how-it-works">See how it will work <span>↗</span></a></div><p class="hero-note">The software is coming soon. Your next idea can start today.</p></div><figure class="hero-visual"><div class="visual-top"><span>${icon('cube')} A new perspective on home</span><span class="pill">3D CONCEPT</span></div><img src="/assets/home-3d.webp" width="1536" height="1024" fetchpriority="high" alt="Concept illustration of a furnished two-bedroom home shown as a 3D cutaway, with an open kitchen and living area"><div class="visual-bottom"><span><i class="dot"></i> Room to imagine more.</span><span>01 / THE POSSIBILITIES</span></div><figcaption>Concept artwork. Not an output from the upcoming editor.</figcaption></figure></section>
<section class="promise-strip" aria-label="Our planned free features"><div class="container promise-items"><span>${icon('plan')} Free 2D floorplans</span><span>${icon('cube')} Free 3D views</span><span>${icon('download')} Free image downloads</span><span>${icon('check')} No payment required</span></div></section>
<section class="section container" id="possibilities"><div class="section-heading"><div><span class="eyebrow">YOUR SPACE, FROM EVERY ANGLE</span><h2>From “what if”<br>to “that’s it.”</h2></div><p>Whether you’re rearranging one room or imagining an entire building, a good floorplan helps you see the possibilities before you move a thing.</p></div><div class="feature-grid"><article class="feature-card plan-card"><div class="card-art">${plan}</div><div class="card-copy"><span class="eyebrow">01 / GET THE BIG PICTURE</span><h3>Find your flow in 2D.</h3><p>Plan room layouts, understand how spaces connect, and give every idea a place on the page.</p><a class="text-link" href="/guides/2d-vs-3d-floorplans/">Explore 2D and 3D floorplans ${icon('arrow')}</a></div></article><article class="feature-card render-card"><div class="card-art"><img src="/assets/home-3d.webp" width="1536" height="1024" loading="lazy" alt="3D home concept showing the relationship between bedrooms and shared living spaces"><span class="art-tag">CONCEPT ILLUSTRATION</span></div><div class="card-copy"><span class="eyebrow">02 / SEE THE POSSIBILITIES</span><h3>Bring your space into 3D.</h3><p>See your layout from a new angle. Our upcoming planner is being built to make 2D and 3D part of one simple workflow.</p><a class="text-link" href="/planner/">Discover what’s coming ${icon('arrow')}</a></div></article></div><div class="download-banner"><span class="big-icon">${icon('download')}</span><div><h3>Your ideas. Your images. Zero cost.</h3><p>Free image downloads are part of the plan from day one. Create, explore, and keep your floorplan images without a payment step.</p></div><span class="zero">£0<span>planned price</span></span></div></section>
<section class="how-section" id="how-it-works"><div class="container section"><span class="eyebrow">A SIMPLE PATH TO YOUR NEXT SPACE</span><h2>Less learning curve.<br>More creating.</h2><p class="section-intro">The workflow we’re building — from your first wall to a floorplan you can keep.</p><div class="steps"><article><span class="step-number">01</span>${icon('ruler')}<h3>Start with your space.</h3><p>Gather your room measurements and sketch the outline. A few reliable dimensions make a better starting point.</p></article><article><span class="step-number">02</span>${icon('layers')}<h3>Make it your own.</h3><p>Lay out your rooms in 2D, then explore the space in 3D to see how your ideas fit together.</p></article><article><span class="step-number">03</span>${icon('download')}<h3>Keep the big idea.</h3><p>Download images of your 2D and 3D floorplans for free, ready to revisit or share.</p></article></div><a class="text-link" href="/guides/how-to-measure-a-room/">Get a head start: learn how to measure a room ${icon('arrow')}</a></div></section>
<section class="section container" id="planner"><div class="planner-heading"><div><span class="eyebrow">THE NEXT CHAPTER STARTS HERE</span><h2>Your space to create.</h2></div>${status}</div><div class="editor-preview"><div class="editor-toolbar"><span>${icon('plan')} Your future floorplan workspace</span><span>2D <span class="toolbar-divider">/</span> 3D</span></div><div class="editor-canvas"><div class="editor-plan" aria-hidden="true">${plan.replace('id="grid"','id="editor-grid"').replace('url(#grid)','url(#editor-grid)')}</div><div class="coming-card"><span class="coming-icon">${icon('spark')}</span><span class="eyebrow">A LITTLE MORE ROOM TO DEVELOP</span><h3>Coming soon.</h3><p>We’re building a quick, modern floorplan creator. Free to design in 2D and 3D. Free to download your images.</p><p class="muted">The interactive editor isn’t available yet. In the meantime, get your measurements ready.</p><a class="button" href="/guides/how-to-measure-a-room/">Prepare your first floorplan ${icon('arrow')}</a></div></div><div class="editor-footer"><span>${icon('clock')} In development · No launch date announced</span><span>Designed to be completely free</span></div></div></section>
<section class="section container guides-section"><div class="section-heading"><div><span class="eyebrow">GOOD PLANS START WITH A LITTLE KNOW-HOW</span><h2>Make room for inspiration.</h2></div><a class="text-link" href="/guides/">All planning guides ${icon('arrow')}</a></div>${guideCards()}</section>
<section class="section container faq-section" id="faq"><div><span class="eyebrow">A FEW THINGS YOU MIGHT BE WONDERING</span><h2>Clear answers.<br>Better plans.</h2></div><div class="faqs">${[
['Is FreeFloorplan3D really going to be free?','Yes. The planned core experience is completely free: create building floorplans in 2D and 3D and download images without paying. The software is still in development.'],
['Can I create a floorplan right now?','Not yet. The interactive floorplan creator is coming soon, and we haven’t announced a launch date. You can already use our planning guides and download the free measurement checklist to prepare.'],
['What is the difference between a 2D and a 3D floorplan?','A 2D floorplan shows a space from above, making room boundaries, openings and relationships easy to read. A 3D floorplan adds height and perspective to help you visualise the space. Both views are planned for the editor.'],
['Will I be able to download floorplan images for free?','Yes, free image downloads of your 2D and 3D floorplans are part of the planned software. Export formats and image resolution will be confirmed when the editor launches.'],
['Are the images on this website made with the software?','No. The 3D home is concept artwork and the 2D plan is an illustrative diagram. They explain the idea behind the product and are not screenshots or promised output quality.'],
['Can I use a floorplan for building work?','Use your floorplan to explore and communicate ideas. Before building or ordering fitted items, check measurements on site and get any professional drawings or approvals your project requires.']
].map(([q,a])=>`<details><summary>${q}<span aria-hidden="true">+</span></summary><p>${a}</p></details>`).join('')}</div></section>
<section class="final-cta"><div class="container"><span class="eyebrow">YOUR NEXT IDEA DESERVES A FLOORPLAN</span><h2>Start imagining.<br>We’ll make room for the rest.</h2><p>A free floorplan creator for 2D ideas and 3D possibilities. Coming soon.</p><a class="button light" href="/planner/">Explore what’s coming ${icon('arrow')}</a></div></section>`});

export const guides = [
{slug:'how-to-measure-a-room',title:'How to measure a room for a floorplan',tag:'START WITH THE BASICS',icon:'ruler',summary:'A practical checklist for walls, doors and windows, so your first layout starts with better measurements.',intro:'A useful floorplan starts with the room you actually have. Take a rough sketch, a tape measure or suitable distance meter, and a notebook. Work around the room in a consistent direction so you can connect each number to the right wall.',sections:[
['1. Sketch the outline before you measure','Draw the room’s approximate shape and mark each corner. Include alcoves, chimney breasts, columns and built-in cupboards. Give each wall a letter so your measurements remain easy to follow. The first sketch does not need to be to scale.'],
['2. Record every wall segment','Measure between the finished wall surfaces and record the units beside your numbers. For a wall with a recess, record each section as well as the overall span where possible. Avoid mixing centimetres and millimetres without an explicit conversion. If you measure in millimetres, keep that convention throughout your notes.'],
['3. Position doors and windows','For each opening, record its width and distance from a clearly identified corner. Note the door swing direction so your plan shows where the door needs space to open. Record window sill height and opening height if you want to describe the room in 3D.'],
['4. Add heights and fixed features','Measure ceiling height where it changes, including slopes or bulkheads. Mark radiators, steps, structural projections and any fittings that restrict a layout. A clear floor area can still have an obstruction above it, so write down relevant heights as well as floor positions.'],
['5. Check your measurements before drawing','Repeat important measurements. Where practical, compare a wall’s overall length with its component sections. Diagonal measurements can help you notice when a room is not square. If two readings disagree, record the uncertainty and measure again rather than silently averaging them.'],
['6. Keep a usable record','Label the room, date, measurement units and any areas you could not access. Keep photographs alongside your notes if useful. These measurements will give you a head start when the FreeFloorplan3D editor launches. They are planning information; verify critical sizes before construction or purchasing fitted items.']
]},
{slug:'2d-vs-3d-floorplans',title:'2D vs 3D floorplans: which view do you need?',tag:'SEE THE WHOLE PICTURE',icon:'cube',summary:'Understand what each view shows, when to use it, and why the two work better together.',intro:'2D and 3D floorplans explain the same kind of space in different ways. A top-down drawing is useful for organising a layout. A view with height and perspective helps you imagine being there. Neither view improves the underlying measurements on its own.',sections:[
['What a 2D floorplan shows','A 2D floorplan looks down on the building. It typically shows walls, room boundaries, doors and windows, with labels or dimensions where they are available. Removing perspective makes it easier to follow routes between rooms and compare how the floor area is divided.'],
['When to use 2D','Start in 2D when you are working out room positions, door clearances or the relationship between neighbouring spaces. It is also a helpful format for discussing a layout with someone else because there is a consistent overhead view. Always check the units and stated scale before using a drawing to infer a size.'],
['What a 3D floorplan adds','A 3D floorplan adds the vertical dimension. A cutaway or dollhouse view can make wall heights and the arrangement of rooms easier to picture. Furniture and finishes, when present, provide context, but they can also distract from dimensions that still need checking.'],
['When to use 3D','Use 3D to explore how a layout feels and to explain an idea to someone who finds technical drawings hard to read. Perspective can make distances appear different, so return to measured dimensions before making a fit decision. An attractive render is a visual aid, not proof that a product or layout will fit.'],
['A simple workflow that uses both','Gather measurements, organise the layout in 2D, review it in 3D and return to 2D when you want to revise the structure. FreeFloorplan3D is being developed around free 2D and 3D floorplanning with free image downloads. The editor is coming soon; the concept images on this website are not generated by the software.']
]},
{slug:'plan-your-first-floorplan',title:'How to prepare your first building floorplan',tag:'FROM IDEA TO OUTLINE',icon:'plan',summary:'Turn a list of rooms and everyday needs into a clear brief for your next space.',intro:'Before drawing walls, decide what the space needs to do. A short, concrete brief makes it easier to compare ideas without losing track of the rooms and everyday routines that matter.',sections:[
['Start with the purpose of the plan','Are you recording an existing building, considering a new arrangement, or exploring a new building concept? For an existing space, record its measurements and fixed features first. For a concept, label assumptions clearly so nobody mistakes an early idea for a measured survey.'],
['List the rooms and their relationships','Write down the spaces you need and which ones should connect. For example, consider the route from the entrance to the kitchen, or how guests reach a bathroom. Think about noise and privacy as well as proximity: a quiet workspace may need separation from a busy shared room.'],
['Identify what cannot easily move','Mark structural elements, stairs and fixed services where you know their positions. If you do not know whether something can move, flag it as a question rather than building the design around an assumption. Changes to a building may require professional advice and approvals.'],
['Think through everyday movement','Walk through the proposed layout in your imagination. Consider carrying shopping, opening doors and reaching storage. Measure the furniture you intend to use and account for the space needed to operate it. A furniture footprint alone does not include the room needed to pull out a chair or open a cupboard.'],
['Compare a small number of ideas','Keep an initial layout and make a few deliberate alternatives. Change one major relationship at a time so you can explain why an option works better. Review each idea against the same brief, instead of choosing only the most attractive image.'],
['Prepare for the free planner','Keep your room list, measurements and open questions together. The upcoming FreeFloorplan3D software will provide a place to create 2D and 3D building floorplans and download images for free. Until it launches, use the measurement checklist to prepare a clear starting point.']
]}
];
function guideCards(){return `<div class="guide-grid">${guides.map((g,i)=>`<a class="guide-card" href="/guides/${g.slug}/"><div class="guide-art guide-art-${i}">${icon(g.icon)}<span>FIELD NOTES / 0${i+1}</span></div><div class="guide-copy"><span class="eyebrow">${g.tag}</span><h3>${g.title}</h3><p>${g.summary}</p><span class="read-link">Read the guide ${icon('arrow')}</span></div></a>`).join('')}</div>`;}
export function pages(){return {
 '/':home(),
 '/planner/':layout({title:'Free 2D & 3D Floorplan Creator — Coming Soon | FreeFloorplan3D',description:'Our free floorplan editor is coming soon. Discover the planned 2D and 3D workflow, free image downloads, and prepare your room measurements.',path:'/planner/',body:`<section class="container section planner-page">${status}<h1>Your next space<br>starts <span class="blue">right here.</span></h1><p class="lead">A modern home for your big ideas. Our free 2D and 3D floorplan creator is in development.</p><div id="floorplan-app" data-editor-status="coming-soon"><div class="launch-panel"><span class="coming-icon">${icon('plan')}</span><h2>Coming soon.</h2><p>Create building floorplans. Explore them in 2D and 3D. Download your images. All completely free.</p><p>The editor is not available yet, and no launch date has been announced.</p><a class="button" href="/downloads/measurement-checklist.txt" download>Get the free measurement checklist ${icon('download')}</a><a class="text-link" href="/guides/how-to-measure-a-room/">Learn how to measure your space ${icon('arrow')}</a></div></div><div class="planner-promises"><span>${icon('plan')} Free 2D creation</span><span>${icon('cube')} Free 3D views</span><span>${icon('download')} Free image downloads</span></div></section>`}),
 '/guides/':layout({title:'Floorplan Planning Guides: Measure, Plan & Visualise | FreeFloorplan3D',description:'Learn how to measure a room, compare 2D and 3D floorplans, and prepare your first building layout with practical free planning guides.',path:'/guides/',body:`<section class="container section"><span class="eyebrow">THE FLOORPLAN FIELD NOTES</span><h1>A little know-how.<br><span class="blue">A better starting point.</span></h1><p class="lead">Practical planning guides to help you turn an idea into a clearer picture of your space.</p>${guideCards()}</section>`}),
 ...Object.fromEntries(guides.map(g=>['/guides/'+g.slug+'/',layout({title:g.title+' | FreeFloorplan3D',description:g.summary,path:'/guides/'+g.slug+'/',type:'Article',body:`<article class="container article section"><a class="text-link" href="/guides/">← All planning guides</a><span class="eyebrow">${g.tag}</span><h1>${g.title}</h1><p class="lead">${g.intro}</p><div class="article-body">${g.sections.map(([heading,text])=>`<section><h2>${heading}</h2><p>${text}</p></section>`).join('')}<aside class="article-callout"><h2>Ready for your first outline?</h2><p>Save the free measurement checklist and gather the details of your space.</p><a class="button" href="/downloads/measurement-checklist.txt" download>Download the checklist ${icon('download')}</a><a class="text-link" href="/planner/">Explore the upcoming free planner ${icon('arrow')}</a></aside><h2>Keep planning</h2>${guides.filter(x=>x.slug!==g.slug).map(x=>`<p><a href="/guides/${x.slug}/">${x.title} →</a></p>`).join('')}</div></article>`})])),
 '/privacy/':layout({title:'Website Privacy | FreeFloorplan3D',description:'How this FreeFloorplan3D website handles visitor information while the floorplan software is in development.',path:'/privacy/',body:`<article class="container article section"><span class="eyebrow">THE DETAILS</span><h1>Website privacy.</h1><p class="lead">This page describes the current informational website. The floorplan editor is still in development.</p><div class="article-body"><h2>Information on this website</h2><p>We do not provide account registration, a mailing-list form or floorplan uploads on this website. The measurement checklist downloads directly to your device. We do not receive measurements you write in your downloaded copy.</p><h2>Hosting and technical information</h2><p>Cloudflare hosts and delivers this website. When you visit, network and security processing may include your IP address, requested URL, browser information and request time. Cloudflare handles information according to its <a href="https://www.cloudflare.com/privacypolicy/">privacy policy</a>.</p><h2>Cookies and analytics</h2><p>This website does not add advertising cookies, third-party analytics scripts or browser storage for tracking. Hosting security features may process technical information to deliver and protect the site.</p><h2>When the editor launches</h2><p>We will update this notice to explain any additional processing before enabling accounts, saving projects or collecting information through the editor.</p></div></article>`}),
 '/404.html':layout({title:'Page not found | FreeFloorplan3D',description:'Find your way back to FreeFloorplan3D.',path:'/404.html',noindex:true,body:`<section class="container section"><span class="eyebrow">404 / A SMALL DETOUR</span><h1>This room isn’t<br>on the plan.</h1><p class="lead">We couldn’t find that page. Let’s get you back to the possibilities.</p><a class="button" href="/">Back to the homepage ${icon('arrow')}</a></section>`})
};}
