"use client";
import { useMemo, useState } from "react";
import type { Room } from "@/lib/types";
import type { HeatingProject } from "@/lib/heatingDocument";
import { CONSTRUCTION_TEMPLATES, ENERGY_DISCLAIMER, newAssembly, type ConstructionAssembly, type EnergyProject, type ElementAssignment } from "@/lib/energyDocument";
import { addInsulation, assignEnergyElements, calculateAssemblyUValue, calculateIndicativeEnergyRating, calculateInsulationUpgrade, calculateMaterialQuantities, compareThermalScenarios, energyResults, duplicateRetrofitScenario, findInsulationThickness, scenarioAssignments, type EnergyElement } from "@/lib/energyCalculations";
import { buildEnergyPdf, insulationScheduleCsv } from "@/lib/energyExport";
import styles from "./HeatingLayoutPanel.module.css";

const TABS = ["Overview", "Fabric", "Insulation", "Openings", "Upgrades", "Energy", "Results"] as const;
function NumberField({ label, value, onChange, min = 0, max = 10000, nullable = false }: { label: string; value: number | null; onChange: (v: number | null) => void; min?: number; max?: number; nullable?: boolean }) {
  const [draft, setDraft] = useState<string | null>(null);
  const commit = () => { const raw = draft ?? String(value ?? ""), n = Number(raw);if (raw === "" && nullable) onChange(null);else if (raw !== "" && Number.isFinite(n) && n >= min && n <= max) onChange(n);setDraft(null); };
  return <label>{label}<input type="number" min={min} max={max} step="any" placeholder={nullable ? "Not set" : undefined} value={draft ?? value ?? ""} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur(); }} /></label>;
}
const fmt = (value: number | null, digits = 1) => value === null ? "Not set" : value.toFixed(digits);
function download(bytes: BlobPart, type: string, name: string) { const url = URL.createObjectURL(new Blob([bytes], { type })), a = document.createElement("a");a.href = url;a.download = name;a.click();setTimeout(() => URL.revokeObjectURL(url), 30000); }
export function EnergyLayoutPanel({ rooms, data, heating, onChange, onHeatingChange, selectedIds, onSelect, onUndo, onRedo, canUndo, canRedo, projectName }: { rooms: Room[]; data: EnergyProject; heating: HeatingProject; onChange: (data: EnergyProject) => void; onHeatingChange: (data: HeatingProject) => void; selectedIds: string[]; onSelect: (ids: string[]) => void; onUndo: () => void; onRedo: () => void; canUndo: boolean; canRedo: boolean; projectName: string }) {
  const [tab, setTab] = useState<typeof TABS[number]>("Overview"), [assemblyId, setAssemblyId] = useState(""), [template, setTemplate] = useState(0), [materialId, setMaterialId] = useState("pir-tw55"), [thickness, setThickness] = useState(100), [position, setPosition] = useState<"Inside" | "Outside" | "Within">("Outside"), [error, setError] = useState(""), [busy, setBusy] = useState(false);
  const result = useMemo(() => energyResults(rooms, heating, data), [rooms, heating, data]), comparison = useMemo(() => compareThermalScenarios(rooms, heating, data), [rooms, heating, data]), quantities = useMemo(() => calculateMaterialQuantities(rooms, heating, data), [rooms, heating, data]);
  const existing = comparison[0].result, selected = result.elements.filter(e => selectedIds.includes(e.elementId)), first = selected[0], assignments = scenarioAssignments(data), assembly = data.assemblies.find(a => a.assemblyId === assemblyId), material = data.materials.find(m => m.materialId === materialId);
  const update = (next: EnergyProject) => { setError("");onChange(next); };
  const setting = (key: keyof EnergyProject["energySettings"], value: number | string | null) => update({ ...data, energySettings: { ...data.energySettings, [key]: value } });
  const editAssembly = (patch: Partial<ConstructionAssembly>) => { if (assembly) update({ ...data, assemblies: data.assemblies.map(a => a.assemblyId === assembly.assemblyId ? { ...a, ...patch } : a) }); };
  const assign = (patch: Partial<ElementAssignment>) => update(assignEnergyElements(data, selected.map(e => ({ ...assignments.find(a => a.elementId === e.elementId), elementId: e.elementId, assemblyId: null, uValue: null, geometrySignature: e.geometrySignature, ...patch }))));
  const patchAssignment = (patch: Partial<ElementAssignment>) => update(assignEnergyElements(data, selected.map(e => ({ assemblyId: null, uValue: null, ...assignments.find(a => a.elementId === e.elementId), elementId: e.elementId, geometrySignature: e.geometrySignature, ...patch }))));
  const newScenario = (name = "Proposed Upgrade") => { const scenarioId = crypto.randomUUID();update({ ...data, activeScenarioId: scenarioId, scenarios: [...data.scenarios, { scenarioId, name: `${name} ${data.scenarios.length + 1}`, assignments: [] }] }); };
  const choose = (e: EnergyElement) => { onSelect([e.elementId]);setTab(e.category === "window" || e.category === "door" ? "Openings" : "Fabric");const a = assignments.find(a => a.elementId === e.elementId);if (a?.assemblyId) setAssemblyId(a.assemblyId); };
  const selector = (filter = result.elements) => <div><label>Select a thermal element<select aria-label="Thermal element" value={first?.elementId ?? ""} onChange={e => onSelect(e.target.value ? [e.target.value] : [])}><option value="">Choose element…</option>{filter.map(e => <option key={e.elementId} value={e.elementId}>{e.label} · {e.boundary}</option>)}</select></label><div className={styles.actions}><button onClick={() => onSelect(result.elements.filter(e => e.category === "wall" && e.boundary === "External").map(e => e.elementId))}>All external walls</button><button onClick={() => onSelect(result.elements.filter(e => e.category === "roof" && e.boundary === "External").map(e => e.elementId))}>All exposed ceilings</button><button onClick={() => onSelect(result.elements.filter(e => e.category === "floor" && !["Heated", "Adiabatic"].includes(e.boundary)).map(e => e.elementId))}>All exposed floors</button><button onClick={() => onSelect([])}>Clear selection</button></div><small>{selected.length} selected. Shift-click on the thermal map to add/remove elements.</small></div>;
  const inspector = first && <div><h3>Thermal inspector</h3><p>{first.label} · {first.boundary}</p><p>Area {first.areaM2.toFixed(1)} m² · U {first.uValue.toFixed(3)} W/m²K · ΔT {first.deltaTK.toFixed(1)} K · loss {Math.round(first.heatLossW)} W</p><p>Existing U {fmt(existing.elements.find(e => e.elementId === first.elementId)?.uValue ?? null, 3)} · selected U {fmt(first.uValue, 3)}</p>{first.warnings.map(w => <p key={w} className={styles.warning}>{w}</p>)}<details><summary>Calculation details</summary><p>Q = U × area × ΔT. {first.uValue.toFixed(3)} × {first.areaM2.toFixed(2)} × {first.deltaTK.toFixed(1)} = {Math.round(first.heatLossW)} W.</p><p>Geometry is measured in mm. Opening area is deducted from opaque walls. Equally heated partitions are not external losses.</p></details></div>;
  async function exportPdf() { setBusy(true);try { const bytes = await buildEnergyPdf(rooms, heating, data, projectName);download(new Uint8Array(bytes).buffer, "application/pdf", "energy-insulation-report.pdf"); } catch (e) { setError(e instanceof Error ? e.message : "Could not export report."); } finally { setBusy(false); } }
  return <div className={styles.panel}>
    <div className={styles.actions}><label><input type="checkbox" checked={data.enabled} onChange={e => update({ ...data, enabled: e.target.checked })} /> Energy overlay</label><button onClick={onUndo} disabled={!canUndo}>Undo energy</button><button onClick={onRedo} disabled={!canRedo}>Redo energy</button></div>
    <label>Building scenario<select aria-label="Building scenario" value={data.activeScenarioId ?? ""} onChange={e => update({ ...data, activeScenarioId: e.target.value || null })}><option value="">Existing Building</option>{data.scenarios.map(s => <option key={s.scenarioId} value={s.scenarioId}>{s.name}</option>)}</select></label>
    <small>The selected fabric scenario is used immediately by Heating Layout. Emitters and manually edited pipe paths are retained.</small>
    <div className={styles.tabs} role="tablist" aria-label="Energy & Insulation tabs">{TABS.map(t => <button key={t} role="tab" aria-selected={t === tab} onClick={() => setTab(t)}>{t}</button>)}</div>
    {error && <p role="alert" className={styles.warning}>{error}</p>}
    {tab === "Overview" && <>
      <h3>One building model, multiple calculations</h3><p>Inspect the fabric already drawn, test upgrades and see Heating Layout use the same thermal inputs. Approximate assumptions remain visible.</p>
      {inspector}
      <dl className={styles.totals}><dt>Floor area</dt><dd>{result.areaM2.toFixed(1)} m²</dd><dt>Design heat loss</dt><dd>{(result.designW / 1000).toFixed(1)} kW</dd><dt>Heat-loss coefficient</dt><dd>{Math.round(result.coefficient.total)} W/K</dd><dt>Area-weighted fabric U</dt><dd>{fmt(result.averageU, 2)} W/m²K</dd><dt>Change from existing</dt><dd>{((existing.designW - result.designW) / 1000).toFixed(1)} kW</dd></dl>
      {!result.verified && <p className={styles.warning}>Incomplete construction data: fallback values shown; not verified.</p>}
      <div className={styles.actions}><button onClick={() => setTab("Fabric")}>Define construction</button><button onClick={() => { if (!data.activeScenarioId) newScenario();setTab("Insulation"); }}>Improve insulation</button></div>
      <details><summary>Shared building settings</summary><div className={styles.grid}><NumberField label="External design temperature °C" value={heating.buildingSettings.externalDesignTemperatureC} min={-50} max={25} onChange={v => onHeatingChange({ ...heating, buildingSettings: { ...heating.buildingSettings, externalDesignTemperatureC: v! } })} /><NumberField label="Building ACH" value={heating.buildingSettings.airChangeRate} max={10} onChange={v => onHeatingChange({ ...heating, buildingSettings: { ...heating.buildingSettings, airChangeRate: v! } })} /></div><small>These are Heating Layout&apos;s inputs, not a separate copy. Room overrides remain respected.</small>{rooms.map(r => { const h = result.rooms.find(v => v.room.id === r.id)!;return <p key={r.id}>{r.name}: {h.loss.targetC}°C, ACH {h.loss.ach}. Edit room-specific temperatures/ACH in Heating Layout.</p>; })}</details>
      <details><summary>Layer visibility</summary>{Object.entries(data.display).map(([key, value]) => <label key={key}><input type="checkbox" checked={value} onChange={e => update({ ...data, display: { ...data.display, [key]: e.target.checked } })} />{key}</label>)}</details>
      <p className={styles.warning}>{result.warnings[0]}</p>
    </>}
    {tab === "Fabric" && <>
      {selector()}{inspector}
      {selected.length > 0 && <details open><summary>Assign to selected elements ({selected.length})</summary><label>Construction<select value={assemblyId} onChange={e => setAssemblyId(e.target.value)}><option value="">Choose construction…</option>{data.assemblies.map(a => <option key={a.assemblyId} value={a.assemblyId}>{a.name}</option>)}</select></label><button disabled={!assembly || selected.some(e => e.category !== assembly.category)} onClick={() => assign({ assemblyId, uValue: null })}>Assign construction</button><NumberField label="Entered whole-element U W/m²K (overrides layers)" value={assignments.find(a => a.elementId === first?.elementId)?.uValue ?? null} max={10} nullable onChange={v => assign({ uValue: v, assemblyId: null })} /><label>Boundary / adjacency<select value={assignments.find(a => a.elementId === first?.elementId)?.boundary ?? "Auto"} onChange={e => patchAssignment({ boundary: e.target.value as ElementAssignment["boundary"] })}>{["Auto", "External", "Heated", "Unheated", "Adiabatic", ...(selected.every(e => e.category === "floor") ? ["Ground"] : [])].map(b => <option key={b}>{b}</option>)}</select></label><small>Party walls to equally heated spaces: Heated/Adiabatic. Unknown adjacency must be confirmed. Explicit overrides apply to the selected elements.</small><NumberField label="Adjacent space temperature °C (Heated/Unheated)" value={assignments.find(a => a.elementId === first?.elementId)?.adjacentTemperatureC ?? null} min={-50} max={40} nullable onChange={v => { patchAssignment({ adjacentTemperatureC: v ?? undefined }); }} /></details>}
      <h3>Reusable construction assemblies</h3><label>Starting template<select value={template} onChange={e => setTemplate(Number(e.target.value))}>{CONSTRUCTION_TEMPLATES.map((t, i) => <option key={t.name} value={i}>{t.name}</option>)}</select></label><button onClick={() => { const a = newAssembly(CONSTRUCTION_TEMPLATES[template]);update({ ...data, assemblies: [...data.assemblies, a] });setAssemblyId(a.assemblyId); }}>Add construction</button>
      <label>Edit construction<select value={assemblyId} onChange={e => setAssemblyId(e.target.value)}><option value="">Choose construction…</option>{data.assemblies.map(a => <option key={a.assemblyId} value={a.assemblyId}>{a.name}</option>)}</select></label>
      {assembly && <>
        <label>Construction name<input value={assembly.name} onChange={e => editAssembly({ name: e.target.value })} /></label><label>Category<select value={assembly.category} onChange={e => editAssembly({ category: e.target.value as ConstructionAssembly["category"] })}>{["wall", "floor", "roof", "window", "door"].map(c => <option key={c}>{c}</option>)}</select></label><div className={styles.grid}><NumberField label="Rsi m²K/W" value={assembly.rsi} max={10} onChange={v => editAssembly({ rsi: v! })} /><NumberField label="Rse m²K/W" value={assembly.rse} max={10} onChange={v => editAssembly({ rse: v! })} /></div><NumberField label="Optional tested whole-assembly U (overrides layers)" value={assembly.directUValue} min={.001} max={10} nullable onChange={v => editAssembly({ directUValue: v })} />
        <small>Outside → inside. Cavities need a supplied thermal resistance, not an invented conductivity. Parallel timbers/bridges are not accounted for by this simple serial-layer model.</small>
        {assembly.layers.map((l, i) => <fieldset key={l.layerId}><legend>Layer {i + 1} {l.upgrade ? "(upgrade)" : ""}</legend><label>Material<select value={l.materialId} onChange={e => editAssembly({ layers: assembly.layers.map(v => v.layerId === l.layerId ? { ...v, materialId: e.target.value } : v) })}>{data.materials.map(m => <option key={m.materialId} value={m.materialId}>{m.name}</option>)}</select></label><div className={styles.grid}><NumberField label={`Layer ${i + 1} thickness mm`} value={l.thicknessMm} max={3000} onChange={v => editAssembly({ layers: assembly.layers.map(item => item.layerId === l.layerId ? { ...item, thicknessMm: v! } : item) })} /><NumberField label={`Layer ${i + 1} entered R (optional)`} value={l.resistanceOverride} max={100} nullable onChange={v => editAssembly({ layers: assembly.layers.map(item => item.layerId === l.layerId ? { ...item, resistanceOverride: v } : item) })} /></div><div className={styles.actions}><button disabled={i === 0} onClick={() => { const layers = [...assembly.layers];[layers[i - 1], layers[i]] = [layers[i], layers[i - 1]];editAssembly({ layers }); }}>Move layer up</button><button disabled={i === assembly.layers.length - 1} onClick={() => { const layers = [...assembly.layers];[layers[i], layers[i + 1]] = [layers[i + 1], layers[i]];editAssembly({ layers }); }}>Move layer down</button><button onClick={() => editAssembly({ layers: assembly.layers.filter(v => v.layerId !== l.layerId) })}>Remove layer</button></div></fieldset>)}
        <button onClick={() => editAssembly({ layers: [...assembly.layers, { layerId: crypto.randomUUID(), materialId: "pir-tw55", thicknessMm: 100, resistanceOverride: null, position: "Within", upgrade: false }] })}>Add layer</button>
        {(() => { const c = calculateAssemblyUValue(assembly, data.materials);return <div><p>Total R {fmt(c.totalR, 3)} m²K/W · U {fmt(c.uValue, 3)} W/m²K</p><details><summary>How was U calculated?</summary><p>{c.method}; Rsi {assembly.rsi} + Rse {assembly.rse}</p>{c.layers.map(({ layer, resistance }) => <p key={layer.layerId}>{data.materials.find(m => m.materialId === layer.materialId)?.name}: {layer.thicknessMm} mm / 1000 / λ = R {fmt(resistance, 3)} {layer.resistanceOverride !== null ? "(entered override)" : ""}</p>)}{c.uValue === null && <p className={styles.warning}>Not set: complete missing material λ / cavity R values.</p>}</details></div>; })()}
        <label>Construction notes<textarea value={assembly.notes} onChange={e => editAssembly({ notes: e.target.value })} /></label><button onClick={() => { const copy = structuredClone(assembly);copy.assemblyId = crypto.randomUUID();copy.name += " — copy";update({ ...data, assemblies: [...data.assemblies, copy] });setAssemblyId(copy.assemblyId); }}>Duplicate construction for proposal</button>
      </>}
      <details><summary>Thermal material library — edit / add</summary><label>Material<select value={materialId} onChange={e => setMaterialId(e.target.value)}>{data.materials.map(m => <option key={m.materialId} value={m.materialId}>{m.name}</option>)}</select></label>{material && <><label>Material name<input value={material.name} onChange={e => update({ ...data, materials: data.materials.map(m => m.materialId === materialId ? { ...m, name: e.target.value } : m) })} /></label><NumberField label="Material conductivity λ W/mK" value={material.lambda} min={.001} max={20} nullable onChange={v => update({ ...data, materials: data.materials.map(m => m.materialId === materialId ? { ...m, lambda: v, reference: `User-entered conductivity; original reference: ${m.reference}`.slice(0, 2000) } : m) })} /><label>Dataset / product reference<input value={material.reference} onChange={e => update({ ...data, materials: data.materials.map(m => m.materialId === materialId ? { ...m, reference: e.target.value } : m) })} /></label><small>Product-specific samples are not generic family values. Confirm suitability, thickness dependence and moisture conditions.</small></>}<button onClick={() => { const id = crypto.randomUUID();update({ ...data, materials: [...data.materials, { materialId: id, name: "Custom material", category: "Construction", lambda: null, density: null, vapourResistance: null, editable: true, reference: "User supplied" }] });setMaterialId(id); }}>Add custom material</button></details>
    </>}
    {tab === "Insulation" && <>
      {selector(result.elements.filter(e => !["window", "door"].includes(e.category)))}{inspector}
      {!data.activeScenarioId && <button onClick={() => newScenario()}>Create proposed upgrade scenario</button>}
      <label>Insulation material<select value={materialId} onChange={e => setMaterialId(e.target.value)}>{data.materials.filter(m => m.category === "Insulation").map(m => <option key={m.materialId} value={m.materialId}>{m.name}</option>)}</select></label><small>λ {material?.lambda ?? "Not set"} W/mK. Product selection is a thermal assumption, not approval for a particular installation.</small>
      <div className={styles.grid}><NumberField label="Additional insulation thickness mm" value={thickness} min={1} max={1500} onChange={v => setThickness(v!)} /><label>Installation position<select value={position} onChange={e => setPosition(e.target.value as typeof position)}><option>Outside</option><option>Inside</option><option>Within</option></select></label></div><button disabled={!data.activeScenarioId || !selected.length || !material?.lambda || selected.some(e => e.category === "window" || e.category === "door")} onClick={() => { try { update(addInsulation(data, selected, materialId, thickness, position)); } catch (e) { setError(e instanceof Error ? e.message : "Cannot apply insulation."); } }}>Add insulation to selected elements</button>
      {first && material?.lambda && <><h3>Thickness comparison — selected assembly</h3>{[25, 50, 75, 100, 120, 150].map(mm => <p key={mm}>{mm} mm → U {fmt(calculateInsulationUpgrade(first.uValue, material.lambda!, mm), 3)} W/m²K</p>)}<NumberField label={`Selected target U W/m²K (${first.category})`} value={data.targets[first.category]} min={.001} max={10} onChange={v => update({ ...data, targets: { ...data.targets, [first.category]: v! } })} /><p>Approximate additional thickness: {fmt(findInsulationThickness(first.uValue, data.targets[first.category], material.lambda), 0)} mm. Practical increments below:</p>{[25, 50, 75, 100, 120, 150, 200, 250, 300].map(mm => { const u = calculateInsulationUpgrade(first.uValue, material.lambda!, mm)!;return <p key={mm}>{mm} mm · U {u.toFixed(3)} {u <= data.targets[first.category] ? "✓ Meets selected target U-value" : "Above target"}</p>; })}<small>No regulatory compliance or condensation/fire-safety judgement is implied.</small></>}
    </>}
    {tab === "Openings" && <>
      {selector(result.elements.filter(e => e.category === "window" || e.category === "door"))}{inspector}
      {first && (first.category === "window" || first.category === "door") && <><NumberField label="Whole-opening U W/m²K (glass + frame)" value={assignments.find(a => a.elementId === first.elementId)?.uValue ?? null} min={.001} max={10} nullable onChange={v => assign({ uValue: v })} /><label>Glazing type (description, not an assumed U)<select value={assignments.find(a => a.elementId === first.elementId)?.glazingType ?? "Custom / not set"} onChange={e => patchAssignment({ glazingType: e.target.value })}>{["Custom / not set", "Single glazing", "Older double glazing", "Modern double glazing", "Triple glazing"].map(t => <option key={t}>{t}</option>)}</select></label><label>Frame type<input value={assignments.find(a => a.elementId === first.elementId)?.frameType ?? ""} onChange={e => patchAssignment({ frameType: e.target.value })} /></label><NumberField label="Orientation degrees (optional future solar model)" value={assignments.find(a => a.elementId === first.elementId)?.orientationDeg ?? null} max={360} nullable onChange={v => patchAssignment({ orientationDeg: v })} /><NumberField label="Glazing g-value (stored only, solar gains not calculated)" value={assignments.find(a => a.elementId === first.elementId)?.solarGainValue ?? null} max={1} nullable onChange={v => patchAssignment({ solarGainValue: v })} /><small>Dimensions are read from the floorplan; no re-entry. Use declared whole-product U-values, not centre-pane values.</small></>}
    </>}
    {tab === "Upgrades" && <>
      <div className={styles.actions}><button onClick={() => newScenario()}>New scenario</button><button disabled={!data.activeScenarioId} onClick={() => { update(duplicateRetrofitScenario(data, data.activeScenarioId!)); }}>Duplicate scenario</button><button disabled={!data.activeScenarioId} onClick={() => { if (confirm("Delete this proposed scenario? Existing building and other scenarios are kept.")) update({ ...data, activeScenarioId: null, scenarios: data.scenarios.filter(s => s.scenarioId !== data.activeScenarioId) }); }}>Delete scenario</button></div>
      {data.activeScenarioId && <label>Scenario name<input value={data.scenarios.find(s => s.scenarioId === data.activeScenarioId)?.name ?? ""} onChange={e => update({ ...data, scenarios: data.scenarios.map(s => s.scenarioId === data.activeScenarioId ? { ...s, name: e.target.value } : s) })} /></label>}
      {comparison.map(s => <fieldset key={s.scenarioId ?? "existing"}><legend>{s.name}</legend><p>{(s.result.designW / 1000).toFixed(1)} kW · H {Math.round(s.result.coefficient.total)} W/K · reduction {(s.reductionW / 1000).toFixed(1)} kW ({existing.designW ? (100 * s.reductionW / existing.designW).toFixed(0) : 0}%)</p><p>Useful annual heat: {s.result.annual ? `~${Math.round(s.result.annual.usefulKwh / 100) * 100} kWh` : "Not set"}</p><button onClick={() => update({ ...data, activeScenarioId: s.scenarioId })}>Use this scenario in Heating</button></fieldset>)}
      {data.activeScenarioId && data.scenarios.find(s => s.scenarioId === data.activeScenarioId)?.assignments.map(a => <p key={a.elementId}>{result.elements.find(e => e.elementId === a.elementId)?.label ?? `${a.elementId} (geometry missing)`} <button onClick={() => update({ ...data, scenarios: data.scenarios.map(s => s.scenarioId === data.activeScenarioId ? { ...s, assignments: s.assignments.filter(v => v.elementId !== a.elementId) } : s) })}>Remove upgrade override</button></p>)}
      <h3>Largest heat-loss contributors</h3>{result.ranking.slice(0, 10).map(e => <button className={styles.listItem} key={e.elementId} onClick={() => choose(e)}>{e.label}: {Math.round(e.heatLossW)} W · U {e.uValue.toFixed(2)}</button>)}
    </>}
    {tab === "Energy" && <>
      <h3>Indicative annual space heating</h3><p>H × heating degree days × 24 / 1000 × schedule factor. This is separate from peak design heat loss.</p><p>Shared system: {heating.heatingSystem.name}, {heating.heatingSystem.flowTemperatureC}/{heating.heatingSystem.returnTemperatureC}°C. Heating temperature is not annual efficiency.</p>
      <div className={styles.grid}><NumberField label="Heating degree days K·days (annual)" value={data.energySettings.heatingDegreeDays} max={15000} nullable onChange={v => setting("heatingDegreeDays", v)} /><NumberField label="HDD base temperature °C" value={data.energySettings.baseTemperatureC} max={30} onChange={v => setting("baseTemperatureC", v)} /></div><label>Climate source — location, year and base-temperature reference<input placeholder="Enter the source of your degree-day value" value={data.energySettings.climateReference} onChange={e => setting("climateReference", e.target.value)} /></label><NumberField label="Explicit heating schedule multiplier 0–1" value={data.energySettings.scheduleFactor} max={1} onChange={v => setting("scheduleFactor", v)} /><NumberField label="Seasonal efficiency / heat-pump SPF (ratio, optional)" value={data.energySettings.seasonalEfficiency} min={.01} max={10} nullable onChange={v => setting("seasonalEfficiency", v)} /><label>Efficiency basis / system reference<input value={data.energySettings.efficiencyBasis} onChange={e => setting("efficiencyBasis", e.target.value)} /></label>
      <p>Useful heat: {result.annual ? `~${Math.round(result.annual.usefulKwh / 100) * 100} kWh/year` : "Not set"}</p><p>Delivered energy: {result.annual?.deliveredKwh != null ? `~${Math.round(result.annual.deliveredKwh / 100) * 100} kWh/year` : "Not set"}</p><p>Useful heat intensity: {result.usefulIntensity !== null ? `~${Math.round(result.usefulIntensity)} kWh/m²/year` : "Not set"}</p><small>Not a bill forecast. No hot water, solar gains, PV, lighting or annual mixed-fuel allocation. Base temperature embodies assumed gains; do not additionally subtract arbitrary gains. The schedule multiplier is your simplifying assumption, not a dynamic occupancy model.</small>
      <h3>Indicative energy rating</h3><p>{calculateIndicativeEnergyRating().reason}</p><p>{ENERGY_DISCLAIMER}</p>
    </>}
    {tab === "Results" && <>
      <h3>Heat-loss breakdown</h3>{result.categories.map(c => <p key={c.category}>{c.category}: {(c.lossW / 1000).toFixed(1)} kW</p>)}<p>Ventilation: {(result.ventilationW / 1000).toFixed(1)} kW</p><p>Design total: {(result.designW / 1000).toFixed(1)} kW (includes shared design allowance)</p>
      {result.rooms.map(r => <details key={r.room.id}><summary>{r.room.name} · {Math.round(r.loss.designW)} W</summary><p>Area {r.loss.areaM2.toFixed(1)} m²; volume {r.loss.volumeM3.toFixed(1)} m³; {r.loss.targetC}°C; ACH {r.loss.ach}</p>{r.loss.surfaces.map((s, index) => <p key={`${s.key}:${index}`}>{s.label}: {s.areaM2.toFixed(1)} m² × {s.uValue.toFixed(3)} × {Math.max(0, r.loss.targetC - s.adjacentTemperatureC).toFixed(1)} K = {Math.round(s.lossW)} W</p>)}<p>Ventilation: 0.33 × {r.loss.ach} × {r.loss.volumeM3.toFixed(1)} × {Math.max(0, r.loss.targetC - result.outside).toFixed(1)} = {Math.round(r.loss.ventilationW)} W</p></details>)}
      <h3>Insulation quantities</h3><NumberField label="Separate order waste allowance %" value={data.energySettings.wastePercent} max={100} onChange={v => setting("wastePercent", v)} />{quantities.length ? quantities.map((q, i) => <p key={i}>{q.element.label} · {q.material} {q.thicknessMm} mm: net {q.areaM2.toFixed(1)} m² / {q.volumeM3.toFixed(2)} m³; order {q.orderAreaM2.toFixed(1)} m² / {q.orderVolumeM3.toFixed(2)} m³.</p>) : <p>No layer-based insulation upgrades in this scenario.</p>}
      <div className={styles.actions}><button disabled={busy} onClick={() => void exportPdf()}>{busy ? "Exporting…" : "Export Energy Report PDF"}</button><button onClick={() => download(insulationScheduleCsv(rooms, heating, data), "text/csv", "insulation-schedule.csv")}>Export insulation schedule CSV</button></div>
      {result.warnings.map(w => <p key={w} className={styles.warning}>{w}</p>)}
    </>}
    <p className={styles.disclaimer}>{ENERGY_DISCLAIMER}</p>
  </div>;
}
