"use client";
import { useMemo, useState } from "react";
import type { Room } from "@/lib/types";
import type { HeatingProject } from "@/lib/heatingDocument";
import { ENERGY_DISCLAIMER, newAssembly, CONSTRUCTION_TEMPLATES, type ConstructionAssembly, type ConstructionLayer, type EnergyProject } from "@/lib/energyDocument";
import { assignEnergyElements, calculateAssemblyUValue, energyResults, scenarioAssignments } from "@/lib/energyCalculations";
import { assemblyThickness, fabricTargetScore, LAYER_COLOURS, minimumInsulationThickness, resizeAssembly, setWallAssembly, wallThicknessForElement } from "@/lib/energyWallConstruction";
import { buildEnergyPdf } from "@/lib/energyExport";
import { WallLayersPreview } from "./WallLayersPreview";
import styles from "./HeatingLayoutPanel.module.css";

function NumberField({ label, value, onChange, min = 0, max = 10000 }: { label: string; value: number | null; onChange: (v: number | null) => void; min?: number; max?: number }) {
  const [draft, setDraft] = useState<string | null>(null);
  const commit = () => { const raw = draft ?? String(value ?? ""), n = Number(raw);if (!raw) onChange(null);else if (Number.isFinite(n) && n >= min && n <= max) onChange(n);setDraft(null); };
  return <label>{label}<input type="number" min={min} max={max} step="any" placeholder="Not set" value={draft ?? value ?? ""} onChange={e => setDraft(e.target.value)} onBlur={commit} onKeyDown={e => { if (e.key === "Enter") e.currentTarget.blur(); }} /></label>;
}

export function EnergyLayoutPanel({ rooms, data, heating, onChange, onHeatingChange, selectedIds, onSelect, onUndo, onRedo, canUndo, canRedo, projectName }: { rooms: Room[]; data: EnergyProject; heating: HeatingProject; onChange: (data: EnergyProject) => void; onHeatingChange: (data: HeatingProject) => void; selectedIds: string[]; onSelect: (ids: string[]) => void; onUndo: () => void; onRedo: () => void; canUndo: boolean; canRedo: boolean; projectName: string }) {
  const [tab, setTab] = useState<"Walls" | "Results">("Walls"), [error, setError] = useState(""), [template, setTemplate] = useState(0), [materialId, setMaterialId] = useState("pir-tw55"), [targetMode, setTargetMode] = useState("U-value"), [powerTarget, setPowerTarget] = useState(100), [insulationLambda, setInsulationLambda] = useState<number | null>(null), [busy, setBusy] = useState(false);
  const result = useMemo(() => energyResults(rooms, heating, data), [rooms, heating, data]);
  const walls = result.elements.filter(e => e.category === "wall"), first = walls.find(e => selectedIds.includes(e.elementId)), assignments = scenarioAssignments(data);
  const assigned = assignments.find(a => a.elementId === first?.elementId), assembly = data.assemblies.find(a => a.assemblyId === assigned?.assemblyId);
  const construction = assembly ? calculateAssemblyUValue(assembly, data.materials) : null, material = data.materials.find(m => m.materialId === materialId), score = fabricTargetScore(result.elements, data);
  const update = (next: EnergyProject) => { setError("");onChange(next); };
  const edit = (a: ConstructionAssembly) => { if (!first) return;const total = assemblyThickness(a);if (total < 1 || total > 2000) { setError("Overall wall thickness must be between 1 and 2000 mm.");return; }update(setWallAssembly(data, first, { ...a, directUValue: null })); };
  const layerEdit = (id: string, patch: Partial<ConstructionLayer>) => { if (assembly) edit({ ...assembly, layers: assembly.layers.map(l => l.layerId === id ? { ...l, ...patch } : l) }); };
  const targetU = targetMode === "U-value" ? data.targets.wall : first && first.areaM2 * first.deltaTK > 0 ? powerTarget / (first.areaM2 * first.deltaTK) : null;
  const chosenLambda = insulationLambda ?? material?.lambda ?? null;
  const suggested = assembly && targetU ? minimumInsulationThickness(assembly, data, chosenLambda, targetU) : null;
  async function exportPdf() { setBusy(true);try { const bytes = await buildEnergyPdf(rooms, heating, data, projectName), url = URL.createObjectURL(new Blob([new Uint8Array(bytes).buffer], { type: "application/pdf" })), a = document.createElement("a");a.href = url;a.download = "energy-insulation-report.pdf";a.click();setTimeout(() => URL.revokeObjectURL(url), 30000); } catch (e) { setError(e instanceof Error ? e.message : "Export failed."); } finally { setBusy(false); } }
  return <div className={styles.panel}>
    <div className={styles.actions}><label><input type="checkbox" checked={data.enabled} onChange={e => update({ ...data, enabled: e.target.checked, display: { ...data.display, walls: true, labels: true, heatLoss: true } })} /> Energy overlay</label><button onClick={onUndo} disabled={!canUndo}>Undo energy</button><button onClick={onRedo} disabled={!canRedo}>Redo energy</button></div>
    <p><strong>Overall heating loss: {(result.designW / 1000).toFixed(2)} kW</strong> · H {Math.round(result.coefficient.total)} W/K</p>
    <div className={styles.tabs} role="tablist" aria-label="Energy & Insulation tabs">{(["Walls", "Results"] as const).map(t => <button key={t} role="tab" aria-selected={t === tab} onClick={() => setTab(t)}>{t}</button>)}</div>
    {error && <p role="alert" className={styles.warning}>{error}</p>}
    {tab === "Walls" && <>
      <label>Select wall<select aria-label="Select wall" value={first?.elementId ?? ""} onChange={e => onSelect(e.target.value ? [e.target.value] : [])}><option value="">Select a wall on the plan or here…</option>{walls.map(e => <option key={e.elementId} value={e.elementId}>{e.label} · {e.boundary}</option>)}</select></label>
      {data.scenarios.length > 0 && <details><summary>Saved construction scenario</summary><select aria-label="Building scenario" value={data.activeScenarioId ?? ""} onChange={e => update({ ...data, activeScenarioId: e.target.value || null })}><option value="">Existing Building</option>{data.scenarios.map(s => <option key={s.scenarioId} value={s.scenarioId}>{s.name}</option>)}</select><small>Other saved scenarios are retained.</small></details>}
      {!first && <p>Click a coloured wall to edit its construction. Dimensions come from the floorplan.</p>}
      {first && <div key={first.elementId}>
        <h3>{first.label}</h3><p>Area {first.areaM2.toFixed(1)} m² · U {construction?.uValue != null ? construction.uValue.toFixed(3) : assigned?.uValue != null ? assigned.uValue.toFixed(3) : "Not set"} W/m²K · heat loss {Math.round(first.heatLossW)} W{construction?.uValue == null && assigned?.uValue == null ? " (fallback estimate)" : ""}</p>
        <NumberField label="Overall wall thickness mm" value={wallThicknessForElement(first, rooms)} min={1} max={2000} onChange={v => { if (v && assembly) edit(resizeAssembly(assembly, v));else if (v) edit(newAssembly({ name: first.label, category: "wall", materials: [["custom-0", v]] })); }} />
        <small>Layer thicknesses add up to the floorplan wall thickness. Editing overall thickness in either window resizes layers proportionally; edit individual layers for a specific construction. Room boundaries are not moved.</small>
        {!assembly && <><p>No layer composition defined. Current U {first.uValue.toFixed(2)} is a Heating Layout assumption, not a layer calculation.</p><label>Starting composition<select value={template} onChange={e => setTemplate(Number(e.target.value))}>{CONSTRUCTION_TEMPLATES.filter(t => t.category === "wall").map((t, i) => <option key={t.name} value={i}>{t.name}</option>)}</select></label><button onClick={() => edit(resizeAssembly(newAssembly(CONSTRUCTION_TEMPLATES.filter(t => t.category === "wall")[template]), wallThicknessForElement(first, rooms)))}>Define wall layers</button><button onClick={() => edit(newAssembly({ name: first.label, category: "wall", materials: [["custom-0", wallThicknessForElement(first, rooms)]] }))}>Start custom wall</button></>}
        <WallLayersPreview assembly={assembly ?? { assemblyId: first.elementId, name: first.label, category: "wall", rsi: .13, rse: .04, directUValue: null, notes: "", layers: [{ layerId: "undefined-wall", materialId: "undefined-wall", thicknessMm: wallThicknessForElement(first, rooms), resistanceOverride: null, position: "Within", upgrade: false, colorHex: "#c4b09b" }] }} materials={data.materials} />
        {assembly && <><p>Outside → inside. Add, remove or reorder the layers below.</p>
          {assembly.layers.map((l, i) => { const m = data.materials.find(m => m.materialId === l.materialId);return <fieldset key={l.layerId}><legend>Layer {i + 1} · {Number(l.thicknessMm.toFixed(2))} mm</legend>
            <label>Layer {i + 1} material<select value={l.materialId} onChange={e => layerEdit(l.layerId, { materialId: e.target.value, lambdaOverride: null, resistanceOverride: null })}>{data.materials.filter(m => m.category !== "Equivalent resistance").map(m => <option key={m.materialId} value={m.materialId}>{m.name}</option>)}</select></label>
            <div className={styles.grid}><NumberField label={`Layer ${i + 1} thickness mm`} value={l.thicknessMm} min={.1} max={2000} onChange={v => { if (v) layerEdit(l.layerId, { thicknessMm: v }); }} /><label>Layer {i + 1} colour<input type="color" style={{ height: 40, padding: 4 }} value={l.colorHex ?? LAYER_COLOURS[i % LAYER_COLOURS.length]} onChange={e => layerEdit(l.layerId, { colorHex: e.target.value })} /></label></div>
            <div className={styles.grid}><NumberField label={`Layer ${i + 1} conductivity λ W/mK`} value={l.lambdaOverride ?? m?.lambda ?? null} min={.001} max={20} onChange={v => layerEdit(l.layerId, { lambdaOverride: v, resistanceOverride: null })} /><NumberField label={`Layer ${i + 1} entered resistance R (cavity / tested layer)`} value={l.resistanceOverride} max={100} onChange={v => layerEdit(l.layerId, { resistanceOverride: v })} /></div>
            <small>R {construction?.layers[i]?.resistance?.toFixed(3) ?? "Not set"} m²K/W · {m?.reference}</small>
            <div className={styles.actions}><button disabled={!i} onClick={() => { const layers = [...assembly.layers];[layers[i - 1], layers[i]] = [layers[i], layers[i - 1]];edit({ ...assembly, layers }); }}>Move layer {i + 1} up</button><button disabled={i === assembly.layers.length - 1} onClick={() => { const layers = [...assembly.layers];[layers[i], layers[i + 1]] = [layers[i + 1], layers[i]];edit({ ...assembly, layers }); }}>Move layer {i + 1} down</button><button disabled={assembly.layers.length === 1} onClick={() => edit({ ...assembly, layers: assembly.layers.filter(v => v.layerId !== l.layerId) })}>Remove layer {i + 1}</button></div>
          </fieldset>; })}
          <button onClick={() => edit({ ...assembly, layers: [...assembly.layers, { layerId: crypto.randomUUID(), materialId, thicknessMm: 25, resistanceOverride: null, position: "Inside", upgrade: true, colorHex: LAYER_COLOURS[assembly.layers.length % LAYER_COLOURS.length] }] })}>Add layer</button>
          <p><strong>Calculated U: {construction?.uValue?.toFixed(3) ?? "Not set — complete every λ or R"} W/m²K</strong></p>
          <details><summary>Calculation details & wall properties</summary><div className={styles.grid}><NumberField label="Inside surface resistance Rsi" value={assembly.rsi} max={10} onChange={v => { if (v !== null) edit({ ...assembly, rsi: v }); }} /><NumberField label="Outside surface resistance Rse" value={assembly.rse} max={10} onChange={v => { if (v !== null) edit({ ...assembly, rse: v }); }} /></div><p>R = thickness / 1000 / λ (or entered R); U = 1 / (Rsi + ΣR + Rse). Total R {construction?.totalR?.toFixed(3) ?? "Not set"}.</p><p>Wall loss = U × {first.areaM2.toFixed(2)} m² × {first.deltaTK.toFixed(1)} K. One-dimensional model; thermal bridges and moisture need professional assessment.</p><label>Wall boundary<select value={assigned?.boundary ?? "Auto"} onChange={e => update(assignEnergyElements(data, [{ ...assigned, elementId: first.elementId, assemblyId: assembly.assemblyId, uValue: null, geometrySignature: first.geometrySignature, boundary: e.target.value as "Auto" | "External" | "Heated" | "Unheated" | "Adiabatic" }]))}>{["Auto", "External", "Heated", "Unheated", "Adiabatic"].map(v => <option key={v}>{v}</option>)}</select></label><NumberField label="Adjacent temperature °C" value={assigned?.adjacentTemperatureC ?? null} min={-50} max={40} onChange={v => update(assignEnergyElements(data, [{ ...assigned, elementId: first.elementId, assemblyId: assembly.assemblyId, uValue: null, adjacentTemperatureC: v ?? undefined }]))} /></details>
          <h3>Find minimum additional insulation</h3><label>Insulation material<select value={materialId} onChange={e => { setMaterialId(e.target.value);setInsulationLambda(null); }}>{data.materials.filter(m => m.category === "Insulation").map(m => <option key={m.materialId} value={m.materialId}>{m.name}</option>)}</select></label>
          <NumberField label="Selected insulation conductivity λ W/mK" value={chosenLambda} min={.001} max={20} onChange={setInsulationLambda} /><small>Entered conductivity applies to this added insulation only, not other walls or the library.</small><label>Target type<select value={targetMode} onChange={e => setTargetMode(e.target.value)}><option>U-value</option><option>Wall power loss</option></select></label>
          {targetMode === "U-value" ? <NumberField label="Target wall U W/m²K" value={data.targets.wall} min={.001} max={10} onChange={v => { if (v) update({ ...data, targets: { ...data.targets, wall: v } }); }} /> : <NumberField label="Target wall power loss W at design temperature" value={powerTarget} min={.1} max={100000} onChange={v => { if (v) setPowerTarget(v); }} />}
          <p>{suggested === null ? "Complete the wall layers and insulation λ. A power target needs positive area and temperature difference." : suggested === 0 ? "This wall already meets your target." : `Minimum additional insulation: ${suggested} mm (λ ${chosenLambda}); target U ${targetU?.toFixed(3)} W/m²K.`}</p>
          <button disabled={!suggested || assemblyThickness(assembly) + suggested > 2000} onClick={() => { if (suggested) edit({ ...assembly, layers: [...assembly.layers, { layerId: crypto.randomUUID(), materialId, thicknessMm: suggested, lambdaOverride: chosenLambda, resistanceOverride: null, position: "Inside", upgrade: true, colorHex: "#e9c844" }] }); }}>Apply suggested insulation</button><small>Mathematical minimum for this serial-layer model, rounded up to 1 mm. Choose an available product thickness and confirm moisture, fire and installation suitability.</small>
        </>}
      </div>}
    </>}
    {tab === "Results" && <>
      <h3>Overall results</h3><dl className={styles.totals}><dt>Overall heating loss</dt><dd>{(result.designW / 1000).toFixed(2)} kW</dd><dt>Floor area</dt><dd>{result.areaM2.toFixed(1)} m²</dd><dt>Heat-loss coefficient</dt><dd>{Math.round(result.coefficient.total)} W/K</dd><dt>Fabric target score</dt><dd>{score.score === null ? "Not set" : `${score.score}/100`}</dd><dt>Defined fabric coverage</dt><dd>{score.coveragePercent}%</dd></dl>
      <small>Score = area-weighted min(1, your target U / actual U) × 100 for explicitly defined exposed fabric. 100 means your selected targets are met, not an EPC or annual energy score. Undefined elements are excluded; coverage shows how much fabric is assessed.</small>
      <details><summary>Edit project U-value targets used in the score</summary>{Object.entries(data.targets).map(([key, v]) => <NumberField key={key} label={`${key} target U W/m²K`} value={v} min={.001} max={10} onChange={n => { if (n) update({ ...data, targets: { ...data.targets, [key]: n } }); }} />)}</details>
      {result.categories.map(c => <p key={c.category}>{c.category}: {(c.lossW / 1000).toFixed(2)} kW</p>)}<p>Ventilation: {(result.ventilationW / 1000).toFixed(2)} kW</p>
      {result.rooms.map(r => <p key={r.room.id}>{r.room.name}: {Math.round(r.loss.designW)} W · {r.loss.targetC}°C · ACH {r.loss.ach}</p>)}
      <details><summary>Shared heating design assumptions</summary><NumberField label="External design temperature °C" value={heating.buildingSettings.externalDesignTemperatureC} min={-50} max={25} onChange={v => { if (v !== null) onHeatingChange({ ...heating, buildingSettings: { ...heating.buildingSettings, externalDesignTemperatureC: v } }); }} /><NumberField label="Building ACH" value={heating.buildingSettings.airChangeRate} max={10} onChange={v => { if (v !== null) onHeatingChange({ ...heating, buildingSettings: { ...heating.buildingSettings, airChangeRate: v } }); }} /><small>Shared with Heating Layout; room overrides remain respected.</small></details>
      <h3>Official UK U-value guidance</h3><p>Select your nation and applicable edition. New-build, extension and renovation requirements differ; check transitional provisions. These links do not certify this model.</p>
      <p><a href="https://www.gov.uk/government/publications/conservation-of-fuel-and-power-approved-document-l" target="_blank" rel="noreferrer">England — Approved Document L and applicable editions</a></p><p><a href="https://www.gov.wales/approved-document-l-conservation-fuel-and-power" target="_blank" rel="noreferrer">Wales — Approved Document L</a></p><p><a href="https://www.gov.scot/collections/building-standards/" target="_blank" rel="noreferrer">Scotland — Technical Handbooks, Section 6</a></p><p><a href="https://www.finance-ni.gov.uk/articles/building-regulations-technical-booklets" target="_blank" rel="noreferrer">Northern Ireland — Technical Booklet F1 and amendments</a></p>
      <button disabled={busy} onClick={() => void exportPdf()}>{busy ? "Exporting…" : "Export Energy Report PDF"}</button>{!result.verified && <p className={styles.warning}>Some fabric inputs are incomplete. Heating fallback assumptions are included in overall loss, not claimed as calculated layer values.</p>}
    </>}
    <p className={styles.disclaimer}>{ENERGY_DISCLAIMER}</p>
  </div>;
}
