"use client";
import { useState } from "react";
import { assetRepository } from "@/lib/assetRepository";
import type { AssetDefinition, AssetInstance } from "@/lib/projectDocument";

export function LocalAssetLibrary({ assets, instances, onImport, onChange, onClose }: { assets: AssetDefinition[]; instances: AssetInstance[]; onImport: (asset: AssetDefinition) => void; onChange: (instances: AssetInstance[]) => void; onClose: () => void }) {
  const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function add(file?: File) { if (!file) return; setBusy(true); setError(""); try { onImport(await assetRepository.importLocalAsset(file)); } catch (e) { setError(e instanceof Error ? e.message : "Model import failed."); } finally { setBusy(false); } }
  return <div className="modal-backdrop catalogue-backdrop"><section className="settings-dialog local-assets" role="dialog" aria-modal="true" aria-label="Local 3D models"><header><h2>My 3D models</h2><button onClick={onClose} aria-label="Close models">×</button></header><p>Import a self-contained GLB (up to 50 MB). Models stay in this browser and travel with your .floorplan3d backup.</p><p>These models are visual only and excluded from fit checks. Bounds and positions below are in millimetres; verify real measurements independently.</p><input aria-label="Import GLB" type="file" accept=".glb" disabled={busy} onChange={e => { void add(e.target.files?.[0]); e.target.value = ""; }} />{busy && <p>Checking model…</p>}{error && <p role="alert">{error}</p>}{assets.map(asset => <div key={asset.assetId}><strong>{asset.name}</strong><p>{Object.values(asset.computedBoundsMm).map(v => Math.round(v)).join(" × ")} mm (X, Y, Z)</p><button onClick={() => onChange([...instances, { instanceId: crypto.randomUUID(), assetId: asset.assetId, assetVersion: 1, positionMm: { x: 1000, y: 1000, z: 0 }, rotationDeg: { x: 0, y: 0, z: 0 }, scale: { x: 1, y: 1, z: 1 } }])}>Place in 3D</button></div>)}{instances.map((instance, index) => <fieldset key={instance.instanceId}><legend>Placement {index + 1}: {assets.find(a => a.assetId === instance.assetId)?.name}</legend>{(["x", "y", "z"] as const).map(axis => <label key={axis}>{axis.toUpperCase()} (mm)<input type="number" value={instance.positionMm[axis]} min={-100000} max={100000} onChange={e => { if (!e.target.value) return; const v = Number(e.target.value); if (Number.isFinite(v)) onChange(instances.map(i => i.instanceId === instance.instanceId ? { ...i, positionMm: { ...i.positionMm, [axis]: v } } : i)); }} /></label>)}<label>Rotation (degrees)<input type="number" value={instance.rotationDeg.z} onChange={e => onChange(instances.map(i => i.instanceId === instance.instanceId ? { ...i, rotationDeg: { ...i.rotationDeg, z: Number(e.target.value) || 0 } } : i))} /></label><label>Scale<input type="number" min="0.001" max="1000" step="0.1" value={instance.scale.x} onChange={e => { const v = Number(e.target.value); if (v > 0 && v <= 1000) onChange(instances.map(i => i.instanceId === instance.instanceId ? { ...i, scale: { x: v, y: v, z: v } } : i)); }} /></label><button onClick={() => onChange(instances.filter(i => i.instanceId !== instance.instanceId))}>Remove placement</button></fieldset>)}</section></div>;
}
