"use client";
import { useMemo, useRef, useState } from "react";
import type { ProjectDocument } from "@/lib/projectDocument";
import { CURRENCY_OPTIONS, type CurrencyCode } from "@/lib/appPreferences";
import { duplicateQuote, newQuote, newQuoteItem, newQuoteSection, quoteSchema, readQuoteBusinessProfile, saveQuoteBusinessProfile, type QuoteDocument, type QuoteItem, type QuoteParty } from "@/lib/quoteDocument";
import { calculateQuote, changeQuoteCurrency, markupPrice, moneyInput, parseMoney, quoteMoney } from "@/lib/quoteCalculations";
import { generateQuoteItems, quoteCandidates, quoteSourceChanges, refreshQuoteItem } from "@/lib/quoteSources";
import { buildQuotePdf, quotePartyLines, quoteTextBlocks } from "@/lib/quotePdf";
import styles from "./QuoteGenerator.module.css";

function MoneyField({ value, currency, label, onChange }: { value: number | null; currency: CurrencyCode; label: string; onChange: (value: number | null) => void }) {
  const [draft, setDraft] = useState(moneyInput(value, currency));
  const [previous, setPrevious] = useState({ value, currency });
  const [error, setError] = useState("");
  if (value !== previous.value || currency !== previous.currency) {
    setPrevious({ value, currency });
    let parsed: number | null = null; try { parsed = parseMoney(draft, currency); } catch { /* Invalid edits remain visible. */ }
    if (parsed !== value || currency !== previous.currency) setDraft(moneyInput(value, currency));
  }
  return <label><span>{label}</span><input aria-label={label} inputMode="decimal" value={draft} placeholder="Not set" aria-invalid={Boolean(error)} onChange={event => {
    setDraft(event.target.value);
    try { onChange(parseMoney(event.target.value, currency)); setError(""); } catch (cause) { onChange(null); setError(cause instanceof Error ? cause.message : "Invalid price"); }
  }} />{error && <small role="alert">{error}</small>}</label>;
}
function PartyFields({ title, party, supplier, onChange }: { title: string; party: QuoteParty; supplier?: boolean; onChange: (party: QuoteParty) => void }) {
  const fields: Array<[keyof QuoteParty, string]> = [["name", supplier ? "Business name" : "Customer / company"], ["contact", "Contact name"], ["address", "Address"], ["email", "Email"], ["telephone", "Telephone"], ["reference", "Reference"]];
  if (supplier) fields.push(["website", "Website"], ["companyNumber", "Company number"], ["vatNumber", "VAT number"]);
  return <fieldset className={styles.card}><legend>{title}</legend><div className={styles.fields}>{fields.map(([key, label]) => <label key={key}><span>{label}</span>{key === "address" ? <textarea aria-label={`${title} ${label}`} value={party[key]} onChange={event => onChange({ ...party, [key]: event.target.value })} /> : <input aria-label={`${title} ${label}`} type={key === "email" ? "email" : "text"} value={party[key]} onChange={event => onChange({ ...party, [key]: event.target.value })} />}</label>)}</div></fieldset>;
}
export function QuoteCustomerPreview({ quote }: { quote: QuoteDocument }) {
  const totals = calculateQuote(quote);
  return <article className={styles.document} aria-label="Customer quotation preview">
    {/* eslint-disable-next-line @next/next/no-img-element -- Local embedded document logo. */}
    {quote.supplier.logo && <img src={quote.supplier.logo} alt="Business logo" className={styles.logo} />}
    <header><div>{quotePartyLines(quote.supplier, true).map((line, index) => <p key={index}>{line}</p>)}</div><div><h1>QUOTE</h1><p>{quote.quoteNumber}{quote.revision ? ` · Revision ${quote.revision}` : ""}</p><p>Date: {quote.quoteDate || "Not set"}</p>{quote.validUntil && <p>Valid until: {quote.validUntil}</p>}<p>Currency: {quote.currency}</p>{quote.reference && <p>Reference: {quote.reference}</p>}</div></header>
    {quote.exportOptions.customer && <section><h2>Customer</h2>{quotePartyLines(quote.customer).map((line, index) => <p key={index}>{line}</p>)}</section>}
    {quote.exportOptions.project && <section><h2>{quote.projectInfo.name}</h2>{[quote.projectInfo.address, quote.projectInfo.description, quote.projectInfo.reference].filter(Boolean).map((text, index) => <p key={index}>{text}</p>)}</section>}
    {quote.sections.filter(section => section.items.length).map(section => <section key={section.sectionId}><h2>{section.title}</h2>{section.description && <p>{section.description}</p>}<table><thead><tr><th>Description</th><th>Qty</th><th>Unit</th><th>Unit price</th>{quote.taxApplicable && quote.exportOptions.tax && <th>VAT</th>}<th>Total</th></tr></thead><tbody>{section.items.map(item => <tr key={item.quoteItemId}><td>{quote.exportOptions.descriptions ? <>{item.description}{item.notes && <p>{item.notes}</p>}</> : `Item ${totals.lines.findIndex(line => line.item.quoteItemId === item.quoteItemId) + 1}`}</td><td>{item.quantity ?? "Not set"}</td><td>{item.unit}</td><td>{item.unitPriceMinor === null ? "Not set" : quoteMoney(item.unitPriceMinor, quote.currency)}</td>{quote.taxApplicable && quote.exportOptions.tax && <td>{item.taxRate}%</td>}<td>{item.quantity === null || item.unitPriceMinor === null ? "Not set" : quoteMoney(totals.lines.find(line => line.item.quoteItemId === item.quoteItemId)!.subtotal!, quote.currency)}</td></tr>)}</tbody></table></section>)}
    <QuoteTotals quote={quote} />
    {quote.taxApplicable && quote.exportOptions.tax && totals.complete && <section><h2>VAT / tax breakdown</h2>{totals.taxBreakdown.map(band => <p key={band.rate}>{band.rate}% on {quoteMoney(band.net, quote.currency)}: {quoteMoney(band.tax, quote.currency)}</p>)}</section>}
    {quoteTextBlocks(quote).filter(([, text]) => text).map(([label, text]) => <section key={label}><h2>{label}</h2><p>{text}</p></section>)}
  </article>;
}
function QuoteTotals({ quote }: { quote: QuoteDocument }) {
  const totals = calculateQuote(quote);
  return <dl className={styles.totals}>{[["Subtotal", totals.subtotal], ["Discount", totals.discount], [quote.taxApplicable ? "VAT / tax" : "VAT not applicable", totals.tax], ["TOTAL", totals.total]].map(([label, value]) => <div key={String(label)}><dt>{String(label)}</dt><dd>{totals.complete ? quoteMoney(value as bigint, quote.currency) : "Not set"}</dd></div>)}</dl>;
}
function move<T>(items: T[], index: number, direction: number): T[] {
  const result = [...items], next = index + direction;
  if (next < 0 || next >= result.length) return result;
  [result[index], result[next]] = [result[next], result[index]]; return result;
}
export function QuoteGenerator({ project, defaultCurrency, onQuotesChange }: { project: ProjectDocument; defaultCurrency: CurrencyCode; onQuotesChange: (quotes: QuoteDocument[]) => void }) {
  const quotes = project.quotes ?? [];
  const [selectedId, setSelectedId] = useState<string | null>(null);
  const quote = quotes.find(item => item.quoteId === selectedId) ?? quotes[0];
  const [preview, setPreview] = useState(false), [generating, setGenerating] = useState(false), [reviewing, setReviewing] = useState(false);
  const [sourceKeys, setSourceKeys] = useState<string[]>([]), [importPrices, setImportPrices] = useState(false);
  const [selectedLines, setSelectedLines] = useState<string[]>([]), [markup, setMarkup] = useState("10");
  const [message, setMessage] = useState("");
  const [past, setPast] = useState<QuoteDocument[]>([]), [future, setFuture] = useState<QuoteDocument[]>([]);
  const dragItem = useRef<{ sectionId: string; itemId: string } | null>(null);
  const candidates = useMemo(() => quoteCandidates(project, quote?.currency ?? defaultCurrency), [project, quote?.currency, defaultCurrency]);
  const changes = quote ? quoteSourceChanges(quote, candidates) : [];
  const totals = quote ? calculateQuote(quote) : null;
  function replace(next: QuoteDocument, history = true) {
    if (!quote) return;
    const validation = quoteSchema.safeParse(next);
    if (!validation.success) { setMessage(`Change not applied: ${validation.error.issues[0]?.message ?? "Invalid quotation value"}. Your previous quotation is unchanged.`); return; }
    if (history) { setPast(previous => [...previous.slice(-49), structuredClone(quote)]); setFuture([]); }
    onQuotesChange(quotes.map(item => item.quoteId === quote.quoteId ? { ...next, updatedAt: new Date().toISOString() } : item));
  }
  const patch = (values: Partial<QuoteDocument>) => quote && replace({ ...quote, ...values });
  function create(copy?: QuoteDocument, revision = false) {
    if (quotes.length >= 100) { setMessage("This project already contains 100 quotes. Save a separate project or delete an unused quotation first."); return; }
    let supplier: QuoteParty | undefined; try { supplier = readQuoteBusinessProfile(localStorage); } catch { /* Private browsing. */ }
    const next = copy ? duplicateQuote(copy, revision, quotes) : newQuote(project.projectId, project.name, defaultCurrency, quotes, supplier);
    onQuotesChange([...quotes, next]); setSelectedId(next.quoteId); setPast([]); setFuture([]); setPreview(false); setSelectedLines([]);
  }
  function startGeneration() { setSourceKeys(candidates.map(candidate => candidate.key)); setGenerating(true); setPreview(false); }
  function generate() {
    const target = quote ?? newQuote(project.projectId, project.name, defaultCurrency, quotes, (() => { try { return readQuoteBusinessProfile(localStorage); } catch { return undefined; } })());
    const next = generateQuoteItems(target, candidates, sourceKeys, importPrices);
    if (quote) replace(next); else { onQuotesChange([...quotes, next]); setSelectedId(next.quoteId); }
    setGenerating(false); setMessage("Project items copied into an editable snapshot. Review scope and prices before issuing.");
  }
  function itemPatch(sectionId: string, itemId: string, values: Partial<QuoteItem>) {
    if (!quote) return;
    patch({ sections: quote.sections.map(section => section.sectionId === sectionId ? { ...section, items: section.items.map(item => item.quoteItemId === itemId ? { ...item, ...values } : item) } : section) });
  }
  async function exportPdf() {
    if (!quote) return;
    setMessage("Preparing PDF…");
    try {
      const bytes = await buildQuotePdf(quote), blob = new Blob([new Uint8Array(bytes)], { type: "application/pdf" });
      const url = URL.createObjectURL(blob), link = document.createElement("a");
      link.href = url; link.download = `${quote.quoteNumber || "quote"}${quote.revision ? `-R${quote.revision}` : ""}.pdf`; link.click(); setTimeout(() => URL.revokeObjectURL(url), 10000);
      setMessage("PDF exported from the current quotation.");
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "PDF export failed."); }
  }
  async function logo(file: File | undefined) {
    if (!file || !quote) return;
    try {
      if (!/image\/(png|jpeg)/.test(file.type) || file.size > 5 * 1024 * 1024) throw new Error("Choose a PNG or JPEG logo up to 5 MB.");
      const bitmap = await createImageBitmap(file), canvas = document.createElement("canvas");
      const scale = Math.min(1, 500 / Math.max(bitmap.width, bitmap.height)); canvas.width = Math.round(bitmap.width * scale); canvas.height = Math.round(bitmap.height * scale);
      canvas.getContext("2d")!.drawImage(bitmap, 0, 0, canvas.width, canvas.height); bitmap.close();
      const image = canvas.toDataURL("image/png"); if (image.length > 90000) throw new Error("Logo is too complex. Choose a smaller image.");
      patch({ supplier: { ...quote.supplier, logo: image } });
    } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Logo could not load."); }
  }
  return <section className={styles.workspace} aria-label="Quote Generator">
    <header className={styles.heading}><div><span className="pb-eyebrow">PlannerBuild · Commercial</span><h1>Quote Generator</h1><p>Create a professional quotation using your existing PlannerBuild data.</p></div><div className={styles.actions}><button onClick={() => create()}>New quote</button>{quote && <><button onClick={() => create(quote)}>Duplicate quote</button><button onClick={() => create(quote, true)}>Duplicate as revision</button><button onClick={() => { if (window.confirm("Delete this quote only? This cannot be undone.")) { onQuotesChange(quotes.filter(item => item.quoteId !== quote.quoteId)); setSelectedId(null); setPast([]); setFuture([]); } }}>Delete quote</button></>}</div></header>
    {quotes.length > 0 && <label className={styles.selector}><span>Quotation</span><select aria-label="Quotation" value={quote?.quoteId ?? ""} onChange={event => { setSelectedId(event.target.value); setPast([]); setFuture([]); setPreview(false); setSelectedLines([]); }}>{quotes.map(item => <option key={item.quoteId} value={item.quoteId}>{item.quoteNumber}{item.revision ? ` · R${item.revision}` : ""}{item.reference ? ` · ${item.reference}` : ""} · {item.status}</option>)}</select></label>}
    <div className={styles.actions}><button className="pb-primary-button" onClick={startGeneration}>Generate from project</button>{!quote && <button onClick={() => create()}>Start blank quote</button>}{quote && <><button disabled={!past.length} onClick={() => { const previous = past.at(-1)!; setPast(past.slice(0, -1)); setFuture([...future, quote]); replace(previous, false); }}>Undo quote edit</button><button disabled={!future.length} onClick={() => { const next = future.at(-1)!; setFuture(future.slice(0, -1)); setPast([...past, quote]); replace(next, false); }}>Redo quote edit</button><button onClick={() => setPreview(!preview)}>{preview ? "Edit quote" : "Preview"}</button><button className="pb-primary-button" disabled={!totals?.complete} onClick={() => void exportPdf()}>Export PDF</button></>}</div>
    {message && <p role="status">{message}</p>}
    {generating && <fieldset className={styles.card}><legend>Generate quote from project</legend><p>Select quantities and work to include. Activities are fixed-price lots, not inferred labour durations. Separate material quantities may overlap activity scope: review them before generating. Existing source items are not imported twice.</p>{[...new Set(candidates.map(candidate => candidate.group))].map(group => <details key={group} open><summary>{group}</summary><label><input type="checkbox" checked={candidates.filter(candidate => candidate.group === group).every(candidate => sourceKeys.includes(candidate.key))} onChange={event => setSourceKeys(event.target.checked ? [...new Set([...sourceKeys, ...candidates.filter(candidate => candidate.group === group).map(candidate => candidate.key)])] : sourceKeys.filter(key => !candidates.some(candidate => candidate.group === group && candidate.key === key)))} />Include {group}</label>{candidates.filter(candidate => candidate.group === group).map(candidate => <label className={styles.source} key={candidate.key}><input type="checkbox" checked={sourceKeys.includes(candidate.key)} onChange={event => setSourceKeys(event.target.checked ? [...sourceKeys, candidate.key] : sourceKeys.filter(key => key !== candidate.key))} /><span>{candidate.value.description} · {candidate.value.quantity ?? "Not set"} {candidate.value.unit}{candidate.value.trade ? ` · ${candidate.value.trade}` : ""}{candidate.value.internalCostMinor !== null ? ` · entered cost ${quoteMoney(candidate.value.internalCostMinor, quote?.currency ?? defaultCurrency)}` : " · price Not set"}{candidate.value.currency !== (quote?.currency ?? defaultCurrency) ? ` · ${candidate.value.currency} cost not imported; no currency conversion` : ""}</span></label>)}</details>)}{!candidates.length && <p>No project quantities or activities yet. Start a blank quote and add manual items.</p>}<label><input type="checkbox" checked={importPrices} onChange={event => setImportPrices(event.target.checked)} />Use entered internal costs as initial customer prices (editable)</label><div className={styles.actions}><button onClick={generate} disabled={!sourceKeys.length}>Generate</button><button onClick={() => setGenerating(false)}>Cancel generation</button></div></fieldset>}
    {quote && changes.length > 0 && <aside className={styles.card}><strong>Project data changed</strong><p>{changes.length} linked {changes.length === 1 ? "item differs" : "items differ"}. Your quotation has not changed.</p><button onClick={() => setReviewing(!reviewing)}>{reviewing ? "Close updates" : "Review updates"}</button>{reviewing && changes.map(({ item, current }) => <div key={item.quoteItemId} className={styles.review}><strong>{item.description}</strong><p>Quote quantity: {item.quantity ?? "Not set"} {item.unit} · Current project: {current ? `${current.quantity ?? "Not set"} ${current.unit}` : "Source removed"}</p><p>{current && <>Entered internal cost: {item.internalCostMinor === null ? "Not set" : quoteMoney(item.internalCostMinor, quote.currency)} → {current.internalCostMinor === null ? "Not set" : quoteMoney(current.internalCostMinor, quote.currency)}. Source description: {current.description}. </>}Refresh changes quantity/unit and the internal cost snapshot only. Customer price, description and notes stay unchanged.</p><div className={styles.actions}><button onClick={() => { const section = quote.sections.find(section => section.items.some(line => line.quoteItemId === item.quoteItemId))!; itemPatch(section.sectionId, item.quoteItemId, { source: current ? { ...item.source!, baseline: structuredClone(current) } : undefined }); }}>Keep quote</button>{current && <button onClick={() => { const section = quote.sections.find(section => section.items.some(line => line.quoteItemId === item.quoteItemId))!; itemPatch(section.sectionId, item.quoteItemId, refreshQuoteItem(item, current)); }}>Update from project</button>}</div></div>)}</aside>}
    {quote && preview && <div className={styles.scroll}><QuoteCustomerPreview quote={quote} /></div>}
    {quote && !preview && <>
      <div className={styles.columns}><fieldset className={styles.card}><legend>Quote details</legend><div className={styles.fields}>
        {([['quoteNumber', 'Quote number'], ['reference', 'Quote reference'], ['quoteDate', 'Quote date'], ['validUntil', 'Valid until']] as const).map(([field, label]) => <label key={field}><span>{label}</span><input type={field === 'quoteDate' || field === 'validUntil' ? 'date' : 'text'} value={quote[field]} onChange={event => patch({ [field]: event.target.value })} /></label>)}
        <label><span>Currency</span><select aria-label="Currency" value={quote.currency} onChange={event => { const currency = event.target.value as CurrencyCode; if (quote.sections.some(section => section.items.some(item => item.unitPriceMinor !== null)) && !window.confirm("Change currency without exchange-rate conversion? Nominal selling prices are kept (rounded for the new currency). Internal cost snapshots are cleared. Review all prices before issuing.")) return; try { replace(changeQuoteCurrency(quote, currency)); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Currency could not change."); } }}>{CURRENCY_OPTIONS.map(option => <option key={option.code} value={option.code}>{option.code} · {option.symbol}</option>)}</select></label>
        <label><span>Status</span><select aria-label="Status" value={quote.status} onChange={event => patch({ status: event.target.value as QuoteDocument['status'] })}>{['Draft','Sent','Accepted','Rejected','Expired'].map(status => <option key={status}>{status}</option>)}</select></label>
      </div></fieldset><PartyFields title="Customer" party={quote.customer} onChange={customer => patch({ customer })} /></div>
      <details className={styles.card}><summary>Business / contractor and project details</summary><div className={styles.columns}><PartyFields title="Business" supplier party={quote.supplier} onChange={supplier => patch({ supplier })} /><fieldset className={styles.card}><legend>Project information</legend>{(['name','address','description','reference'] as const).map(field => <label key={field}><span>Project {field}</span><textarea value={quote.projectInfo[field]} onChange={event => patch({ projectInfo: { ...quote.projectInfo, [field]: event.target.value } })} /></label>)}</fieldset></div><div className={styles.actions}><label><span>Business logo (PNG / JPEG)</span><input type="file" accept="image/png,image/jpeg" onChange={event => void logo(event.target.files?.[0])} /></label><button onClick={() => patch({ supplier: { ...quote.supplier, logo: "" } })}>Remove logo</button><button onClick={() => { try { saveQuoteBusinessProfile(quote.supplier, localStorage); setMessage("Business profile saved on this device for new quotations."); } catch { setMessage("Could not save business profile. Current quote details are still kept."); } }}>Save business profile</button><button onClick={() => { try { patch({ supplier: readQuoteBusinessProfile(localStorage) }); } catch { setMessage("Profile storage unavailable."); } }}>Load business profile</button></div></details>
      <div className={styles.actions}><h2>Quote items</h2><button onClick={() => patch({ sections: [...quote.sections, newQuoteSection()] })}>Add section</button><label><span>Markup %</span><input inputMode="decimal" value={markup} onChange={event => setMarkup(event.target.value)} list="quote-markup-values" /></label><datalist id="quote-markup-values">{['5','10','15','20'].map(value => <option key={value}>{value}</option>)}</datalist><button onClick={() => { try { patch({ sections: quote.sections.map(section => ({ ...section, items: section.items.map(item => selectedLines.includes(item.quoteItemId) && item.internalCostMinor !== null ? { ...item, unitPriceMinor: markupPrice(item.internalCostMinor, markup) } : item) })) }); setMessage("Markup applied only to selected lines with an entered internal cost."); } catch (cause) { setMessage(cause instanceof Error ? cause.message : "Invalid markup"); } }}>Apply markup to selected lines</button></div>
      {quote.sections.map((section, sectionIndex) => <section key={section.sectionId} className={styles.card}><div className={styles.actions}><label><span>Section name</span><input value={section.title} onChange={event => patch({ sections: quote.sections.map(item => item.sectionId === section.sectionId ? { ...item, title: event.target.value } : item) })} /></label><button disabled={sectionIndex === 0} aria-label={`Move section ${section.title} up`} onClick={() => patch({ sections: move(quote.sections, sectionIndex, -1) })}>↑</button><button disabled={sectionIndex === quote.sections.length - 1} aria-label={`Move section ${section.title} down`} onClick={() => patch({ sections: move(quote.sections, sectionIndex, 1) })}>↓</button><button onClick={() => { if (!section.items.length || window.confirm("Delete this section and its quote items?")) patch({ sections: quote.sections.filter(item => item.sectionId !== section.sectionId) }); }}>Delete section</button><button onClick={() => patch({ sections: quote.sections.map(item => item.sectionId === section.sectionId ? { ...item, items: [...item.items, newQuoteItem()] } : item) })}>Add item</button><strong>Section subtotal: {totals?.complete ? quoteMoney(totals.sections[sectionIndex].subtotal, quote.currency) : "Not set"}</strong></div><label><span>Section description</span><textarea value={section.description} onChange={event => patch({ sections: quote.sections.map(item => item.sectionId === section.sectionId ? { ...item, description: event.target.value } : item) })} /></label>
        <div className={styles.scroll}><table className={styles.editorTable}><thead><tr><th>Select</th><th>Description</th><th>Qty</th><th>Unit</th><th>Unit price</th><th>VAT %</th><th>Total (net)</th><th>Actions</th></tr></thead><tbody>{section.items.map((item, itemIndex) => <tr key={item.quoteItemId} draggable onDragStart={event => { if ((event.target as HTMLElement).closest('input,textarea,select')) { event.preventDefault(); return; } dragItem.current = { sectionId: section.sectionId, itemId: item.quoteItemId }; }} onDragOver={event => event.preventDefault()} onDrop={event => { event.preventDefault(); const source = dragItem.current; if (!source || source.itemId === item.quoteItemId) return; const line = quote.sections.find(group => group.sectionId === source.sectionId)?.items.find(line => line.quoteItemId === source.itemId); if (!line) return; const groups = quote.sections.map(group => ({ ...group, items: group.items.filter(line => line.quoteItemId !== source.itemId) })); const destination = groups.find(group => group.sectionId === section.sectionId)!; destination.items.splice(destination.items.findIndex(line => line.quoteItemId === item.quoteItemId), 0, line); patch({ sections: groups }); dragItem.current = null; }}>
          <td><input type="checkbox" aria-label={`Select quote line ${itemIndex + 1} in ${section.title}`} checked={selectedLines.includes(item.quoteItemId)} onChange={event => setSelectedLines(event.target.checked ? [...selectedLines, item.quoteItemId] : selectedLines.filter(id => id !== item.quoteItemId))} /></td>
          <td><label><span>Description</span><textarea aria-label={`Description ${sectionIndex + 1}.${itemIndex + 1}`} value={item.description} onChange={event => itemPatch(section.sectionId, item.quoteItemId, { description: event.target.value })} /></label>{item.source && <small>Source: {item.source.label} · Linked to project</small>}<details><summary>Notes, room, trade and cost</summary>{(['notes','room','trade'] as const).map(field => <label key={field}><span>{field}</span><input value={item[field]} onChange={event => itemPatch(section.sectionId, item.quoteItemId, { [field]: event.target.value })} /></label>)}<label><span>Cost category</span><select value={item.category} onChange={event => itemPatch(section.sectionId, item.quoteItemId, { category: event.target.value as QuoteItem['category'] })}>{['Labour','Materials','Fixed-price work','Services','Fees','Other'].map(category => <option key={category}>{category}</option>)}</select></label><MoneyField value={item.internalCostMinor} currency={quote.currency} label={`Internal cost ${sectionIndex + 1}.${itemIndex + 1}`} onChange={internalCostMinor => itemPatch(section.sectionId, item.quoteItemId, { internalCostMinor })} /><small>Internal cost is per quoted unit and is never included in customer documents.</small></details></td>
          <td><input aria-label={`Quantity ${sectionIndex + 1}.${itemIndex + 1}`} type="number" min="0" step="any" placeholder="Not set" value={item.quantity ?? ''} onChange={event => itemPatch(section.sectionId, item.quoteItemId, { quantity: /^\d{1,12}(\.\d{1,6})?$/.test(event.target.value) ? event.target.value : null })} /></td>
          <td><input aria-label={`Unit ${sectionIndex + 1}.${itemIndex + 1}`} list="quote-units" value={item.unit} onChange={event => itemPatch(section.sectionId, item.quoteItemId, { unit: event.target.value })} /></td>
          <td><MoneyField value={item.unitPriceMinor} currency={quote.currency} label={`Unit price ${sectionIndex + 1}.${itemIndex + 1}`} onChange={unitPriceMinor => itemPatch(section.sectionId, item.quoteItemId, { unitPriceMinor })} /></td>
          <td><input aria-label={`VAT rate ${sectionIndex + 1}.${itemIndex + 1}`} type="number" min="0" max="100" step="0.0001" disabled={!quote.taxApplicable} value={item.taxRate} onChange={event => { if (/^\d{1,3}(\.\d{1,4})?$/.test(event.target.value) && Number(event.target.value) <= 100) itemPatch(section.sectionId, item.quoteItemId, { taxRate: event.target.value }); }} /></td>
          <td>{totals?.lines.find(line => line.item.quoteItemId === item.quoteItemId)?.subtotal === null ? 'Not set' : quoteMoney(totals!.lines.find(line => line.item.quoteItemId === item.quoteItemId)!.subtotal!, quote.currency)}</td>
          <td><div className={styles.rowActions}><button aria-label={`Move item ${itemIndex + 1} up in ${section.title}`} disabled={itemIndex === 0} onClick={() => patch({ sections: quote.sections.map(group => group.sectionId === section.sectionId ? { ...group, items: move(group.items, itemIndex, -1) } : group) })}>↑</button><button aria-label={`Move item ${itemIndex + 1} down in ${section.title}`} disabled={itemIndex === section.items.length - 1} onClick={() => patch({ sections: quote.sections.map(group => group.sectionId === section.sectionId ? { ...group, items: move(group.items, itemIndex, 1) } : group) })}>↓</button><button onClick={() => patch({ sections: quote.sections.map(group => group.sectionId === section.sectionId ? { ...group, items: [...group.items.slice(0, itemIndex + 1), { ...structuredClone(item), quoteItemId: crypto.randomUUID() }, ...group.items.slice(itemIndex + 1)] } : group) })}>Duplicate item</button><button onClick={() => patch({ sections: quote.sections.map(group => group.sectionId === section.sectionId ? { ...group, items: group.items.filter(line => line.quoteItemId !== item.quoteItemId) } : group) })}>Delete item</button></div></td>
        </tr>)}</tbody></table></div></section>)}
      <datalist id="quote-units">{['hours','days','m²','m','items','rooms','lot','service'].map(unit => <option key={unit}>{unit}</option>)}</datalist>
      <div className={styles.columns}><fieldset className={styles.card}><legend>Discount and VAT / tax</legend><label><span>Quote discount</span><select aria-label="Quote discount" value={quote.discount.type} onChange={event => patch({ discount: { ...quote.discount, type: event.target.value as QuoteDocument['discount']['type'] } })}><option value="none">None</option><option value="percentage">Percentage</option><option value="fixed">Fixed amount ({quote.currency})</option></select></label>{quote.discount.type !== 'none' && <label><span>Discount value</span><input inputMode="decimal" value={quote.discount.value ?? ''} onChange={event => patch({ discount: { ...quote.discount, value: /^\d{1,12}(\.\d{1,6})?$/.test(event.target.value) ? event.target.value : null } })} /></label>}<label><input type="checkbox" checked={quote.taxApplicable} onChange={event => patch({ taxApplicable: event.target.checked })} />VAT / tax applicable</label><p>Not applicable by default. Rates are editable per line; use 0%, 5%, 20% or a custom rate. No tax treatment is assumed.</p></fieldset><div className={styles.card}><QuoteTotals quote={quote} />{totals?.errors.length ? <ul role="alert">{totals.errors.map((error, index) => <li key={index}>{error}</li>)}</ul> : <p>Totals ready. Internal costs and source references are excluded from customer documents.</p>}</div></div>
      <div className={styles.columns}>{(['introduction','scope','exclusions','paymentTerms','notes','footer'] as const).map(field => <label className={styles.card} key={field}><span>{({ introduction:'Introduction',scope:'Scope notes',exclusions:'Exclusions',paymentTerms:'Payment terms',notes:'Additional notes',footer:'Footer' })[field]}</span><textarea value={quote[field]} onChange={event => patch({ [field]: event.target.value })} placeholder="Optional — enter your own text" /></label>)}</div>
      <fieldset className={styles.card}><legend>Customer PDF content</legend><div className={styles.actions}>{Object.entries(quote.exportOptions).map(([key, value]) => <label key={key}><input type="checkbox" checked={value} onChange={event => patch({ exportOptions: { ...quote.exportOptions, [key]: event.target.checked } })} />{({customer:'Customer details',project:'Project details',descriptions:'Item descriptions',tax:'VAT breakdown',scope:'Scope notes',exclusions:'Exclusions',paymentTerms:'Payment terms',notes:'Additional notes'} as Record<string,string>)[key]}</label>)}</div><p>Financial totals are always included.</p></fieldset>
      <div className={styles.actions}><button onClick={() => setPreview(true)}>Preview</button><button className="pb-primary-button" disabled={!totals?.complete} onClick={() => void exportPdf()}>Export PDF</button></div>
    </>}
  </section>;
}
