"use client";
import { useRef, useState, type CSSProperties } from "react";
import type { ConstructionAssembly, ThermalMaterial } from "@/lib/energyDocument";
import { assemblyThickness, LAYER_COLOURS } from "@/lib/energyWallConstruction";
import styles from "./WallLayersPreview.module.css";
export function WallLayersPreview({ assembly, materials }: { assembly: ConstructionAssembly; materials: ThermalMaterial[] }) {
  const [expanded, setExpanded] = useState(false), [minimised, setMinimised] = useState(false), [rotation, setRotation] = useState({ x: -18, y: -35 });
  const drag = useRef<{ x: number; y: number; rx: number; ry: number } | null>(null);
  const total = assemblyThickness(assembly), depth = Math.min(180, Math.max(25, total * .4));
  return <section className={styles.preview} aria-label="Wall composition preview"><div className={styles.header}><strong>Wall composition · {Number(total.toFixed(2))} mm</strong><div><button aria-expanded={!minimised} onClick={() => setMinimised(!minimised)}>{minimised ? "Restore preview" : "Minimise preview"}</button><button aria-pressed={expanded} onClick={() => { setExpanded(!expanded);setMinimised(false); }}>{expanded ? "Reduce preview" : "Expand preview"}</button></div></div>
    {!minimised && <><div className={styles.viewport} role="img" aria-label="Rotatable wall layer stack. Drag to rotate or use the rotation sliders." style={{ height: expanded ? 420 : 230 }} onPointerDown={e => { drag.current = { x: e.clientX, y: e.clientY, rx: rotation.x, ry: rotation.y };e.currentTarget.setPointerCapture(e.pointerId); }} onPointerMove={e => { if (drag.current) setRotation({ x: Math.max(-80, Math.min(80, drag.current.rx - (e.clientY - drag.current.y) * .5)), y: drag.current.ry + (e.clientX - drag.current.x) * .5 }); }} onPointerUp={() => { drag.current = null; }} onPointerCancel={() => { drag.current = null; }}><div className={styles.stack} style={{ transform: `rotateX(${rotation.x}deg) rotateY(${rotation.y}deg)` }}>{assembly.layers.map((l, i) => { const d = total ? depth * l.thicknessMm / total : 0, z = -depth / 2 + (total ? depth * assembly.layers.slice(0, i).reduce((sum, v) => sum + v.thicknessMm, 0) / total : 0) + d / 2;return <div key={l.layerId} className={styles.block} style={{ "--layer-colour": l.colorHex ?? LAYER_COLOURS[i % LAYER_COLOURS.length], "--layer-depth": `${d}px`, transform: `translateZ(${z}px)` } as CSSProperties}><div className={styles.front} style={{ transform: `translateZ(${d / 2}px)` }} /><div className={styles.back} style={{ transform: `translateZ(${-d / 2}px) rotateY(180deg)` }} /><div className={styles.side} /><div className={styles.left} /><div className={styles.top} /><div className={styles.bottom} /></div>; })}</div></div><small>Outside → inside. Proportional layer depths; illustrative wall sample, not a fit calculation.</small><div className={styles.sliders}><label>Rotate horizontally<input type="range" min={-180} max={180} value={((rotation.y + 180) % 360 + 360) % 360 - 180} onChange={e => setRotation({ ...rotation, y: Number(e.target.value) })} /></label><label>Tilt preview<input type="range" min={-80} max={80} value={rotation.x} onChange={e => setRotation({ ...rotation, x: Number(e.target.value) })} /></label><button onClick={() => setRotation({ x: -18, y: -35 })}>Reset rotation</button></div><ol className={styles.legend}>{assembly.layers.map((l, i) => <li key={l.layerId}><span style={{ background: l.colorHex ?? LAYER_COLOURS[i % LAYER_COLOURS.length] }} />{materials.find(m => m.materialId === l.materialId)?.name} · {Number(l.thicknessMm.toFixed(2))} mm</li>)}</ol></>}
  </section>;
}
