import test from 'node:test';
import assert from 'node:assert/strict';
import { newAssembly, newEnergyProject, parseEnergyProject } from '../lib/energyDocument.ts';
import { calculateAssemblyUValue, calculateLayerResistance, energyElements, scenarioAssignments, withEnergyFabric } from '../lib/energyCalculations.ts';
import { assemblyThickness, fabricTargetScore, minimumInsulationThickness, resizeAssembly, setWallAssembly, syncWallAssemblyThickness } from '../lib/energyWallConstruction.ts';
import { newHeatingProject } from '../lib/heatingDocument.ts';
import { calculateRoomHeatLoss } from '../lib/heatingCalculations.ts';
import type { Room } from '../lib/types.ts';
const m=(value:number)=>({value,uncertainty_mm:0,verified:true,source_type:'USER_MEASURED'});
const room:Room={id:'r',name:'Room',version:1,vertices:[{x:0,y:0},{x:5000,y:0},{x:5000,y:4000},{x:0,y:4000}],wall_height:m(2500),wall_thickness:m(150),openings:[],obstacles:[]};
function setup(){const e=newEnergyProject(),h=newHeatingProject(),el=energyElements([room],h,e)[0],a=newAssembly({name:'Custom',category:'wall',materials:[['brick-english-red',100],['pir-tw55',50]]});return {e,h,el,a};}
test('wall label anchors survive save/load without changing thermal calculations',()=>{
 const {e,h,el}=setup();const before=calculateRoomHeatLoss(room,[room],withEnergyFabric(h,e,[room]));
 e.labelPositions={[el.elementId]:{x:1234.5,y:-321}};const restored=parseEnergyProject(JSON.parse(JSON.stringify(e)));
 assert.deepEqual(restored.labelPositions,e.labelPositions);assert.deepEqual(calculateRoomHeatLoss(room,[room],withEnergyFabric(h,restored,[room])),before);
 assert.throws(()=>parseEnergyProject({...e,labelPositions:{wall:{x:Infinity,y:0}}}));
});
test('layer-local conductivity and colours persist without changing material library',()=>{const {e,a}=setup();a.layers[0].lambdaOverride=.25;a.layers[0].colorHex='#abc123';e.assemblies=[a];assert.equal(calculateLayerResistance(a.layers[0],e.materials),.4);assert.equal(parseEnergyProject(e).assemblies[0].layers[0].colorHex,'#abc123');assert.equal(e.materials.find(m=>m.materialId==='brick-english-red')!.lambda,.45);});
test('overall thickness resizing preserves proportions and clears obsolete whole-U override',()=>{const {a}=setup();a.directUValue=.9;const n=resizeAssembly(a,300);assert.equal(assemblyThickness(n),300);assert.equal(n.layers[0].thicknessMm,200);assert.equal(n.layers[1].thicknessMm,100);assert.equal(n.directUValue,null);assert.equal(assemblyThickness(a),150);});
test('main-floorplan thickness edit resizes active wall construction, not other walls',()=>{const {e,h,el,a}=setup();const next=setWallAssembly(e,el,a),others=energyElements([room],h,next),changed={...room,wall_thickness_overrides_mm:{'wall-001':300}};const synced=syncWallAssemblyThickness(next,others,[changed]);const assigned=scenarioAssignments(synced)[0];assert.equal(assemblyThickness(synced.assemblies.find(a=>a.assemblyId===assigned.assemblyId)!),300);assert.ok(calculateRoomHeatLoss(changed,[changed],withEnergyFabric(h,synced,[changed])).designW<calculateRoomHeatLoss(room,[room],withEnergyFabric(h,next,[room])).designW);assert.equal(scenarioAssignments(synced).length,1);});
test('editing inherited scenario wall clones composition and preserves existing version',()=>{const {e,el,a}=setup();const existing=setWallAssembly(e,el,a),source=existing.existingAssignments[0].assemblyId!;existing.scenarios=[{scenarioId:'p',name:'Proposal',assignments:[]}];existing.activeScenarioId='p';const proposal=setWallAssembly(existing,el,resizeAssembly(existing.assemblies.find(a=>a.assemblyId===source)!,300));assert.equal(assemblyThickness(proposal.assemblies.find(a=>a.assemblyId===source)!),150);assert.notEqual(proposal.scenarios[0].assignments[0].assemblyId,source);});
test('minimum added insulation rounds upward and actually meets U and power targets',()=>{const {e,a,el}=setup();const mm=minimumInsulationThickness(a,e,.022,.2)!;assert.ok(mm>0);const added={...a,layers:[...a.layers,{...a.layers[1],layerId:'extra',thicknessMm:mm}]};assert.ok(calculateAssemblyUValue(added,e.materials).uValue!<=.2);const tooThin={...added,layers:added.layers.map(l=>l.layerId==='extra'?{...l,thicknessMm:mm-1}:l)};assert.ok(calculateAssemblyUValue(tooThin,e.materials).uValue!>.2);const target=20/(el.areaM2*el.deltaTK);assert.ok(minimumInsulationThickness(a,e,.022,target)!>mm);assert.equal(minimumInsulationThickness(a,e,null,.2),null);});
test('fabric score excludes undefined fallback surfaces and exposes coverage',()=>{const {e,h,el,a}=setup();assert.equal(fabricTargetScore(energyElements([room],h,e),e).score,null);const n=setWallAssembly(e,el,a),score=fabricTargetScore(energyElements([room],h,n),n);assert.ok(score.score!>0);assert.ok(score.coveragePercent>0&&score.coveragePercent<100);e.materials.find(m=>m.materialId==='custom-0')!.lambda=null;const unknown={...a,layers:[{...a.layers[0],materialId:'custom-0'}]};const missing=setWallAssembly(e,el,unknown);assert.equal(fabricTargetScore(energyElements([room],h,missing),missing).score,null);});
