export interface WindowHelpStep { heading: string; text: string }
/** Task help, not generic window chrome instructions. Matching is shared across dialogs. */
export function windowHelpSteps(title: string): WindowHelpStep[] {
  if (/heating/i.test(title)) return [{ heading: "One heating catalogue", text: "Opening Heating Layout automatically highlights enlarged heating symbols; closing it removes the overlay while placed elements stay visible. Add heating element opens the same Heating elements catalogue used by Add to plan. Placed objects own their dimensions and technical specifications; legacy hydronic items without ratings receive clearly labelled size-scaled panel estimates, not tested product ratings. Radiators remain visible in the normal plan; select one in heating mode and press Delete to remove it." }, { heading: "Pipes and UFH", text: "Connect heating elements: click two radiators, boilers or manifolds to create hot supply (red) and cooler return (blue) routes. Keep heating pipes square uses the same orthogonal routing as electrical circuits. Boiler central-heating capacity is not counted as room-emitter output. Draw heating pipe: click corners, then Finish pipe. Select a pipe to drag its points; double-click to add a corner and right-click an internal point to remove it. In UFH, create a zone, place/select a manifold, then regenerate explicitly. Existing edited/locked circuits are preserved." }, { heading: "Design and review", text: "Choose a room. Room setup contains its heating method, target temperature and expandable building assumptions. The summary compares heat required with heat available, updating live. Green means the calculated capacity covers heat loss; a green estimated surplus is not confirmed product performance. Amber means a small shortfall or data needing review; red means more output is needed. Select an item in Heating elements to edit dimensions or expand Output & performance. System changes water temperatures; Results compares rooms and exports the plan. Auto Design Heating acts on every room. Published ratings are valid only for their stated products and conditions. Results and exports are preliminary planning information, not certified hydraulic or safety design." }];
  if (/lighting.*test/i.test(title)) return [
    { heading: "Try your switches", text: "Click an individual rocker on the plan or its gang button inside the collapsible circuit section. On/Off labels and lamp highlights give feedback. Reset returns all test positions to their initial state; closing exits testing without changing your design." },
    { heading: "Two-way and multi-gang controls", text: "Connect both switches to the same light using Generic or Control links in the same circuit. Either switch flips the shared light. Two-way contacts use A/A and B/B for On, A/B and B/A for Off; a double-gang plate is two separate controls, not two-way wiring. For multi-gang switches, click the required rocker when connecting, or edit each connection’s From/To gang. Unconnected rockers never operate another rocker’s lights. Dimmer testing is on/off only." },
    { heading: "What this checks", text: "This is logical schematic feedback, not a physical wiring or safety check. Power links are not switch-control links. Crossing bridges mean wires are not connected; use Join crossing in a connection’s editor to create an explicit junction dot. Warnings identify unsupported or missing controls; an electrician must check the real installation." },
  ];
  if (/electrical.*(bom|schedule)/i.test(title)) return [
    { heading: "Review quantities", text: "BOM groups placed fittings into calculated items. Filter by category, room or circuit, then edit order quantities, unit costs and commercial details. Editing an order quantity does not add or remove fittings on the plan." },
    { heading: "Document and export", text: "Add manual items, notes and photos where needed. Use the circuit tab to review connections and drawing-line lengths. Export CSV or use the electrical export window for a report; drawing-line length is not physical cable length." },
  ];
  if (/electrical.*import|import.*electrical/i.test(title)) return [{ heading: "Merge or replace", text: "Merge keeps existing electrical data and adds the imported layout. Replace removes current electrical fittings, connections and circuits, but keeps the floorplan and other project data. Review the counts before choosing; Cancel leaves the project unchanged." }];
  if (/export/i.test(title)) return [{ heading: "Choose output", text: "Choose the available format and document/display options, review the preview when offered, then use Save or Export. The downloaded file is separate from your editable project." }, { heading: "Keep an editable backup", text: "Save the project as a .floorplan3d file if you want to reopen and edit it later. Exported images and PDFs are not editable project backups." }];
  if (/electrical/i.test(title)) return [
    { heading: "Place fittings", text: "Enable Electrical layout mode. Use Add electrical fitting, choose an item and click the plan to place it. The last item stays selected for repeated placement. Escape cancels placement." },
    { heading: "Circuits", text: "A first circuit is always present. Select a circuit before connecting fittings. Rename it and press Enter or leave the field to save. New circuit adds another; the last circuit cannot be deleted." },
    { heading: "Connect and edit", text: "Click Connect, then the source and destination fittings. Double-click Connect to repeat. Escape cancels. Select a connection or choose Edit to change its style, relationship, circuit and label; Ok finishes editing. Delete removes only the connection." },
    { heading: "Routes and labels", text: "Right-click a route to add a corner, drag corners or segments to reshape it, and right-click a corner to remove it. Force horizontal / vertical routes keeps legs axis-aligned. Enable Circuit labels, then drag a label to reposition it without moving its route." },
    { heading: "Check layout", text: "Check layout is shown only while Electrical layout mode is enabled. It opens a temporary lighting test. Two switches linked to the same light can control it from either location. Assign a gang on each connection for multi-gang switches." },
    { heading: "Save and document", text: "Save layout downloads electrical-only data; Load layout merges or replaces it. Project save also preserves circuits, connections and label positions. BOM / Schedule handles quantities and notes. Connections are schematic relationships, not verified cable routes or certified electrical design." },
  ];
  if (/define wall layers/i.test(title)) return [{ heading: "Build the wall", text: "Controls are on the left and a live rotating preview is on the right. Open Starting composition for a preset or a custom wall. Open each layer to set its material, thickness and colour; expand Thermal parameters & source for conductivity or tested resistance. Add, remove or reorder layers from outside to inside." }, { heading: "Preview and targets", text: "Drag the preview to rotate, use its zoom slider or Fit. Find minimum additional insulation accepts a U-value or design wall-loss target. Missing thermal properties are not filled in automatically; targets are your choices, not regulatory limits." }, { heading: "Save or cancel", text: "Done saves the draft to the selected wall, updates its floorplan thickness and recalculates heating. Cancel or Close discards the draft without changing the model. If the wall or project changed during editing, cancel and reopen before saving." }];
  if (/energy|insulation/i.test(title)) return [{ heading: "Edit a wall", text: "Select a coloured wall on the plan or in Walls. Choose Define layers to open a dedicated editor with controls on the left and a live preview on the right. Confirm with Done or discard with Cancel. Add, remove and reorder layers there. Enter thickness, material conductivity or cavity resistance, and colours. The wall preview is visible by default. Drag to rotate, then click to enlarge or collapse, just as in Add to plan. Drag U-value/heat-loss labels on the plan to avoid overlaps. Closing this window turns off Energy overlay without deleting construction data." }, { heading: "One shared thickness", text: "Layer depths add up to the drawn wall thickness. Editing overall thickness here or in Build floorplan scales the layer depths proportionally. Entered cavity/tested R stays fixed; review it after resizing. Missing conductivity stays Not set, with fallback estimates labelled on the plan." }, { heading: "Targets and results", text: "Choose a target U or wall power loss and insulation conductivity to find the minimum additional thickness. Apply explicitly; obtain professional moisture/fire advice. Results includes heating demand, a transparent fabric-target score and official national guidance links, these reports are not official EPCs or compliance certificates." }];
  if (/heating/i.test(title)) return [{ heading: "Calculate demand", text: "Heat Loss reads your floorplan rooms. Confirm exposed boundaries, U-values, indoor/outdoor temperatures and ACH. Review the calculation breakdown before sizing emitters." }, { heading: "Design heating", text: "Choose a room heating method and system temperatures, then Auto Design Heating. UFH requires a zone, manifold and pipe settings. Missing product performance is Not set, not an assumed pass." }, { heading: "Edit and review", text: "Move radiators and manifolds, edit exclusions and circuit points, or lock circuits before regeneration. Review Results and warnings, then export. These are preliminary planning calculations requiring professional design review." }];
  if (/view properties/i.test(title)) return [{ heading: "Adjust the view", text: "Use zoom and Fit to frame the project. Toggle the listed overlays such as room names, measurements, wall thickness, annotations and grid. These controls change presentation, not measured geometry." }];
  if (/build floorplan/i.test(title)) return [{ heading: "Draw and edit", text: "Choose the drawing or room tool, click the plan to add geometry, and use Select to edit it. Enter measured dimensions where offered. Undo/Redo reverts the relevant edit history." }, { heading: "Use your existing plan", text: "Import a reference drawing and calibrate it using a known dimension. The reference image is visual guidance; saved millimetre dimensions remain authoritative." }];
  if (/add to plan|object catalogue|local.*asset|asset library/i.test(title)) return [{ heading: "Choose and place", text: "Browse or filter categories and select an item. Review its dimensions and preview, then use the insertion/placement control and click the plan. Escape cancels placement." }, { heading: "Reuse items", text: "The library/catalogue supplies objects; placed instances belong to your project. Keep a project backup including referenced local models. Catalogue administration changes the library rather than an individual placement." }];
  if (/selected object|appearance|dimensions/i.test(title)) return [{ heading: "Edit the selected item", text: "Change the available dimensions, position, rotation, component colours or material finish. Review the preview, then use the window’s confirmation control where present. Reset restores the relevant default." }];
  if (/annotation|marker|line/i.test(title)) return [{ heading: "Annotate the plan", text: "Select a text, line, marker or measurement tool and place it on the plan. Select an existing annotation to edit its content or style. Escape ends the active command; Delete removes the selected annotation." }];
  if (/coordinate/i.test(title)) return [{ heading: "Edit measured points", text: "Review the coordinates of the current room/outline and edit the available numeric fields. Coordinates use the selected display units but saved geometry remains millimetres. Changes may alter room shape and quantities." }];
  if (/preference|setting/i.test(title)) return [{ heading: "Personalise the workspace", text: "Choose System/Light/Dark and Comfortable/Compact. Display units affect formatting, not calculation units. Default currency labels monetary values; changing it does not convert existing amounts. View controls change drawing presentation." }];
  if (/account|plan.*billing/i.test(title)) return [{ heading: "Sign in", text: "Sign in or create an account for cloud features. Confirm your email when required. Local planning and project files remain available without a paid subscription." }, { heading: "Plans and return", text: "Use Plans to choose or manage a subscription. Stripe handles payment confirmation; no payment is made just by choosing a plan. Use Back to planner or close this window to return to your project." }];
  if (/activity|template|schedule|register/i.test(title)) return [{ heading: "Plan activities", text: "Choose a template or enter an activity name, phase, trade, room, dates and costs as available. Save/confirm to add or update it; Cancel leaves the draft unapplied. Review dependencies and entered costs in the schedule/dashboard." }];
  if (/camera/i.test(title)) return [{ heading: "Set the shot", text: "Adjust the camera position, direction and available lens controls. Use the preview to frame your project. Camera settings affect the view, not physical room dimensions." }];
  if (/calibrat/i.test(title)) return [{ heading: "Calibrate your drawing", text: "Select two points defining a known distance, enter the measured length, and confirm. Use a reliable measurement; do not infer accurate dimensions solely from the image." }];
  if (/save|download/i.test(title)) return [{ heading: "Save a project backup", text: "Choose a file name and confirm the download. A .floorplan3d file preserves editable project data and referenced local assets. Keep a copy outside browser storage; a PDF/image export is not an editable backup." }];
  if (/human/i.test(title)) return [{ heading: "Use the reference person", text: "Adjust the human mock-up dimensions and position to visualise scale and clearance. Its visual appearance does not determine whether a product fits; measured geometry and calculations remain authoritative." }];
  if (/privacy/i.test(title)) return [{ heading: "Understand storage", text: "Review which features use local browser storage and which use optional online services. Download project backups for portability. Signing in does not replace the need to keep your own backups." }];
  return [{ heading: `Using ${title}`, text: "Review the fields and options below to adjust this part of the current project. Form labels identify the value being changed. Use the window’s Save, Apply or Ok control where offered; other controls apply immediately. Cancel closes an unapplied draft." }];
}
